import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join,resolve,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {TeamEngine} from '../src/team-engine.mjs';
import {PrototypeRuntime} from '../src/runtime.mjs';
import {capture,changes,applyChanges,rollbackIntegration} from '../src/workspaces.mjs';
import {DurableStore} from '../src/durable-store.mjs';
class Adapter extends EventEmitter {
 records=[];
 async list(owner){return this.records.filter(r=>r.scope===owner).map(({scope,...r})=>structuredClone(r));}
 async reconcile(owner){return this.list(owner);}
 async startMember(input){const r={...input,runId:randomUUID(),threadId:randomUUID(),turnId:randomUUID(),status:'inProgress',connection:'connected',outputs:[],commands:[],events:[],lastObservedAt:new Date().toISOString()};this.records.push(r);const {scope,...result}=r;return result;}
 async close(){}
}
const member=(id,writeScopes)=>({id,writeScopes,role:id,responsibility:'Check fixture',reason:'Independent bounded work'});
const work=(id,memberId)=>({id,memberId,kind:'work',title:id,goal:'Check fixture',acceptance:'Fixture correct',dependencies:[]});
const review=(id,target,memberId)=>({...work(id,memberId),kind:'review',reviewOfTaskId:target,dependencies:[{taskId:target,when:'submitted'}]});
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'team-readiness-regression-')),project=join(root,'project');await mkdir(project);await writeFile(join(project,'a.txt'),'before');const adapter=new Adapter(),engine=new TeamEngine({root:join(root,'data'),runtimeFactory:()=>adapter});const plan={members:[member('a',['a.txt']),member('qa',[]),member('b',['b.txt'])],tasks:[work('a','a'),review('qa-a','a','qa')]};const team=await engine.create('owner',{id:randomUUID(),owner:'owner',mode:'project-selected',project:{projectId:'fixture',root:project}},{goal:'Check bounded fixture independently',plan});const f={root,project,adapter,engine,team};try{await fn(f);}finally{await engine.close();assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.match(root,/team-readiness-regression-/);await rm(root,{recursive:true});}}
const view=f=>f.engine.read('owner',f.team.id);
const start=async f=>f.engine.start('owner',f.team.id,(await view(f)).team.revision);
async function finish(f,r,output={summary:'Checked',decision:'accept',reason:'Actual fixture checked'}){r.status='completed';r.outputs=[{turnId:r.turnId,text:JSON.stringify(output)}];await f.engine.observe(f.team.id,r);}
test('public reconcile DTO settles a disconnected attempt without leaking ownership',()=>fixture(async f=>{await start(f);const r=f.adapter.records[0];r.status='unknown';r.connection='disconnected';await f.engine.observe(f.team.id,r);let v=await view(f);assert.equal(v.team.tasks[0].attempts[0].state,'unknown');await assert.rejects(f.engine.rework('owner',f.team.id,v.team.revision,'a','retry'),/reconcile/);r.status='completed';r.outputs=[{turnId:r.turnId,text:'{"summary":"done"}'}];v=await view(f);await f.engine.reconcile('owner',f.team.id,v.team.revision);v=await view(f);assert.equal(v.team.tasks[0].status,'submitted');assert.equal(v.team.members[0].status,'idle');assert.equal(v.team.dispatchPaused,true);assert.equal(f.adapter.records.length,1);}));
test('accepted start is idempotent, including the final budget slot',()=>fixture(async f=>{await f.engine.store.update(f.team.id,'owner',f.team.revision,t=>{t.totalDispatches=22;});await start(f);await finish(f,f.adapter.records[0]);await finish(f,f.adapter.records[1]);let v=await view(f);assert.equal(v.team.state,'accepted');assert.equal(v.team.totalDispatches,24);await start(f);v=await view(f);assert.equal(v.team.state,'accepted');await f.engine.integrate('owner',f.team.id,v.team.revision);await start(f);assert.equal((await view(f)).team.state,'delivered');}));
test('reviewer constraints apply to edits and leave persisted plan unchanged on rejection',()=>fixture(async f=>{await assert.rejects(f.engine.edit('owner',f.team.id,f.team.revision,'qa-a',{memberId:'b'}),/read-only/);assert.equal((await view(f)).team.tasks[1].memberId,'qa');}));
test('generated coverage is excluded from delivery while source scope violations remain blocked',()=>fixture(async f=>{await start(f);let r=f.adapter.records[0];await mkdir(join(r.cwd,'coverage'));await writeFile(join(r.cwd,'coverage','report.json'),'{}');await finish(f,r);assert.equal((await view(f)).team.tasks[0].status,'submitted');r=f.adapter.records[1];await writeFile(join(r.cwd,'a.txt'),'reviewer mutation');await finish(f,r);assert.equal((await view(f)).team.tasks[1].status,'blocked');}));
test('workspace setup failure before RPC remains retryable and does not consume dispatch budget',()=>fixture(async f=>{await mkdir(join(f.root,'data','execution'));await writeFile(join(f.root,'data','execution',f.team.id),'obstruction');await start(f);const v=await view(f);assert.equal(f.adapter.records.length,0);assert.equal(v.team.tasks[0].attempts[0].state,'setup-failed');assert.equal(v.team.members[0].status,'idle');assert.equal(v.team.totalDispatches,0);assert.equal(v.team.tasks[0].attempt,0);await f.engine.rework('owner',f.team.id,v.team.revision,'a','retry setup');}));
test('valid long review JSON is not truncated',()=>fixture(async f=>{await start(f);await finish(f,f.adapter.records[0]);const r=f.adapter.records[1],rt=new PrototypeRuntime();rt.save=async()=>{};rt.records.set(r.runId,r);const text=JSON.stringify({summary:'evidence '.repeat(1100),decision:'accept',reason:'Checked'});rt.onEvent({method:'item/completed',params:{threadId:r.threadId,turnId:r.turnId,item:{id:'review',type:'agentMessage',text}}});assert.equal(r.outputs[0].text,text);r.status='completed';await f.engine.observe(f.team.id,r);assert.equal((await view(f)).team.state,'accepted');}));
test('unchanged file contents are not duplicated in team state',()=>fixture(async f=>{await writeFile(join(f.project,'asset.bin'),Buffer.alloc(1024*1024,1));await start(f);await finish(f,f.adapter.records[0]);await finish(f,f.adapter.records[1]);assert.ok((await readFile(f.engine.store.document(f.team.id).v2)).length<100000,'team state must contain content references');}));
test('merged version gets an independent final review and failed check cannot deliver',()=>fixture(async f=>{let v=await view(f);await f.engine.addTasks('owner',f.team.id,v.team.revision,[work('b','b'),review('qa-b','b','qa')]);await start(f);await writeFile(join(f.adapter.records[0].cwd,'a.txt'),'after a');await writeFile(join(f.adapter.records[1].cwd,'b.txt'),'after b');await finish(f,f.adapter.records[0]);await finish(f,f.adapter.records[1]);await finish(f,f.adapter.records[2]);await finish(f,f.adapter.records[3]);v=await view(f);assert.notEqual(v.team.state,'accepted');const r=f.adapter.records[4];assert.ok(r,'final merged review must be dispatched');assert.equal(await readFile(join(r.cwd,'a.txt'),'utf8'),'after a');assert.equal(await readFile(join(r.cwd,'b.txt'),'utf8'),'after b');r.commands=[{itemId:'failed-check',status:'completed',exitCode:1}];await finish(f,r,{summary:'Failure',decision:'accept',reason:'Incorrect acceptance'});v=await view(f);assert.notEqual(v.team.state,'accepted');await assert.rejects(f.engine.integrate('owner',f.team.id,v.team.revision),/acceptance/);assert.equal(await readFile(join(f.project,'a.txt'),'utf8'),'before');}));
test('missing dependencies block before dispatch; existing dependencies are copied without sharing writes',()=>fixture(async f=>{
 await writeFile(join(f.project,'package.json'),JSON.stringify({dependencies:{'fixture-package':'1.0.0'}}));await start(f);let v=await view(f);assert.equal(v.team.state,'preparation-blocked');assert.equal(f.adapter.records.length,0);
 const pkg=join(f.project,'node_modules','fixture-package');await mkdir(pkg,{recursive:true});await writeFile(join(pkg,'package.json'),'{"name":"fixture-package","version":"1.0.0"}');await writeFile(join(pkg,'index.js'),'module.exports=42;');
 await start(f);assert.equal(f.adapter.records.length,1);const copied=join(f.adapter.records[0].cwd,'node_modules','fixture-package','index.js');assert.equal(await readFile(copied,'utf8'),'module.exports=42;');await writeFile(copied,'module.exports=0;');assert.equal(await readFile(join(pkg,'index.js'),'utf8'),'module.exports=42;');await finish(f,f.adapter.records[0]);assert.equal((await view(f)).team.tasks[0].status,'submitted');
}));
test('preflight reports all file and total budgets together without dispatch',()=>fixture(async f=>{
 await writeFile(join(f.project,'one.bin'),Buffer.alloc(20));await writeFile(join(f.project,'two.bin'),Buffer.alloc(20));let error;try{await capture(f.project,{maxFileBytes:10,maxTotalBytes:30,maxFiles:2});}catch(e){error=e;}
 assert.deepEqual(error.issues.filter(i=>i.kind==='file-budget').map(i=>i.path),['one.bin','two.bin']);assert.ok(error.issues.some(i=>i.kind==='total-byte-budget'));assert.ok(error.issues.some(i=>i.kind==='file-count-budget'));
}));
test('dead owner lock is quarantined while live owner cannot be stolen',()=>fixture(async f=>{const file=join(f.root,'owned-state');await writeFile(file+'.lock',JSON.stringify({pid:2147483647,token:'dead-fixture-owner'}));const store=new DurableStore(file,{});const release=await store.lock({timeoutMs:30});try{await assert.rejects(store.lock({timeoutMs:5}),/locked/);}finally{await release();}}));
test('nonterminal events on the last dispatch slot do not pause successful completion',()=>fixture(async f=>{await f.engine.store.update(f.team.id,'owner',f.team.revision,t=>{t.totalDispatches=22;});await start(f);await finish(f,f.adapter.records[0]);await f.engine.observe(f.team.id,f.adapter.records[1]);assert.equal((await view(f)).team.dispatchPaused,false);await finish(f,f.adapter.records[1]);assert.equal((await view(f)).team.state,'accepted');}));
test('partial integration rolls back only matching writes and refuses foreign changes',()=>fixture(async f=>{
 await writeFile(join(f.project,'b.txt'),'old b');const before=await capture(f.project);await writeFile(join(f.project,'a.txt'),'new a');await writeFile(join(f.project,'b.txt'),'new b');const after=await capture(f.project),delta=changes(before,after,['.']);await writeFile(join(f.project,'a.txt'),'before');await writeFile(join(f.project,'b.txt'),'old b');let error;try{await applyChanges(f.project,delta,join(f.root,'recovery'),{afterWrite:()=>{throw new Error('injected disk failure');}});}catch(e){error=e;}assert.ok(error.journal);assert.equal(await readFile(join(f.project,'a.txt'),'utf8'),'new a');
 await writeFile(join(f.project,'b.txt'),'user change');await assert.rejects(rollbackIntegration(f.project,error.journal),/user changed/);assert.equal(await readFile(join(f.project,'a.txt'),'utf8'),'new a');assert.equal(await readFile(join(f.project,'b.txt'),'utf8'),'user change');
 await writeFile(join(f.project,'b.txt'),'old b');await rollbackIntegration(f.project,error.journal);await rollbackIntegration(f.project,error.journal);assert.equal(await readFile(join(f.project,'a.txt'),'utf8'),'before');assert.equal(await readFile(join(f.project,'b.txt'),'utf8'),'old b');
}));
test('repeated identical planning reuses the same persisted team',()=>fixture(async f=>{const grant={id:randomUUID(),owner:'owner',mode:'project-selected',project:{projectId:'fixture',root:f.project}},args={goal:'Idempotent bounded work',plan:{members:[member('a',['a.txt']),member('qa',[])],tasks:[work('a','a'),review('qa-a','a','qa')]}};const [a,b]=await Promise.all([f.engine.planOnce('owner',grant,args),f.engine.planOnce('owner',grant,args)]);assert.equal(a.id,b.id);assert.equal(a.totalDispatches,0);}));
test('independent verification may write coverage but cannot change its deliverable',()=>fixture(async f=>{await start(f);await finish(f,f.adapter.records[0]);const r=f.adapter.records[1];assert.equal(r.sandbox,'workspace-write');await mkdir(join(r.cwd,'coverage'));await writeFile(join(r.cwd,'coverage','review.json'),'{"checked":true}');await finish(f,r);assert.equal((await view(f)).team.state,'accepted');assert.deepEqual((await view(f)).team.tasks[1].attempts[0].changedPaths,[]);}));
