import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {NativeMembers} from '../src/native-members.mjs';
import {LeaderEngine} from '../src/leader-engine.mjs';
import {TeamProfiles} from '../src/team-policy.mjs';
import {ModelCatalog} from '../src/model-catalog.mjs';
import {memberWork} from '../src/member-work.mjs';
import {teamResponse} from '../src/team-responses.mjs';
import {TeamArchive as OldArchive} from './fixtures/legacy-archive-v011.mjs';
const member=(id,writes=[])=>({id,role:id,responsibility:'Own '+id,reason:'Specialist',writeScopes:writes});
const jobs=id=>[{id,title:'Implement '+id,goal:'Deliver scoped behavior',acceptance:'Verified behavior',memberId:'dev',priority:3,kind:'work',dependencies:[]},{id:'review-'+id,title:'Review '+id,goal:'Verify independently',acceptance:'Independent evidence',memberId:'qa',priority:3,kind:'review',reviewOfTaskId:id,dependencies:[{taskId:id,when:'submitted'}]}];
async function fixture(options={}){
 const root=await mkdtemp(join(tmpdir(),'team-p0-p1-')),cwd=join(root,'project');await mkdir(cwd);const runs=new Map(),observer={async inspect(l,p,id,marker,opts={}){const r=runs.get(marker);if(!r||r.threadId!==id)throw new Error('Native record unavailable');if(opts.requireIdle&&!r.quiescence)throw new Error('Latest native turn is not confirmed idle');return structuredClone(r);}};
 const engine=new LeaderEngine({root:join(root,'records'),observer}),team=await engine.planOnce('owner',{cwd,threadId:'leader'},{goal:'Implement and independently verify scoped behavior',initializeMembers:true,memberStartup:'on-demand',approvalMode:'auto',execute:true,plan:{members:[member('dev',['src']),member('qa')],tasks:jobs('work')},...options});
 const f={engine,root,cwd,team,runs};f.saved=()=>engine.store.get(team.id,'owner');f.claim=async(taskId='work')=>{const t=await f.saved();return engine.claim('owner',team.id,t.revision,taskId);};f.run=(packet,status='inProgress',extra={})=>runs.set(packet.marker,{threadId:'child-'+packet.memberId,turnId:'turn-'+packet.attemptId,status,model:'host-model',outputs:[],commands:[],...extra});f.bind=async(packet)=>{const t=await f.saved();return engine.bind('owner',team.id,t.revision,packet.taskId,packet.attemptId,'child-'+packet.memberId);};f.ctx=(id='dev')=>({threadId:'child-'+id,parentThreadId:'leader',cwd});return f;
}
test('on-demand roster launches the first ready owner with its task, without initializing reviewers or unrelated roles',async()=>{const f=await fixture(),r=await f.engine.receipt('owner',f.team.id);assert.deepEqual(r.initializations,[]);assert.equal(r.readiness.find(t=>t.taskId==='work').ready,true);assert.equal(r.readiness.find(t=>t.taskId==='review-work').ready,false);const c=await f.claim();assert.equal(c.dispatch.action,'spawn-native-member');assert.ok(c.dispatch.prompt.includes('Allowed source writes: src'));f.run(c.dispatch);const b=await f.bind(c.dispatch);assert.equal(b.team.members[0].rosterVerified,true);assert.equal(b.team.members[1].agentThreadId,null);assert.equal(b.team.tasks[1].attempts.length,0);assert.equal(b.team.tasks[0].attempts[0].executedRoute.model,'host-model');await assert.rejects(()=>f.claim('review-work'),/not ready/);});
test('lazy reservations replay the same attempt and preserve unknown bindings without replacing the native member',async()=>{const f=await fixture(),a=await f.claim(),b=await f.claim();assert.equal(a.dispatch.attemptId,b.dispatch.attemptId);f.run(a.dispatch,'starting',{turnId:null});await f.bind(a.dispatch);await assert.rejects(()=>f.claim(),/not ready/);const t=await f.saved();assert.equal(t.tasks[0].attempts.length,1);assert.equal(t.members[0].agentThreadId,'child-dev');assert.equal(t.totalDispatches,1);});
test('stop covers initialization turns, cannot report unknown as halted, and resume requires confirmed idle and reason',async()=>{const f=await fixture({memberStartup:'eager'});let t=await f.saved();for(const m of t.members){f.runs.set(m.rosterMarker,{threadId:'child-'+m.id,turnId:'init-'+m.id,status:'inProgress',outputs:[],commands:[]});await f.engine.bindRoster('owner',t.id,t.revision,m.id,'child-'+m.id);t=await f.saved();}
 const request={requestId:randomUUID(),reason:'用户要求暂停所有成员'},stop=await f.engine.stop('owner',t.id,t.revision,request);assert.equal(stop.leaderAction.targets.length,2);assert.ok(stop.leaderAction.targets.every(x=>x.initialization));assert.equal(stop.team.executionControl.status,'stopping');assert.equal((await f.engine.stop('owner',t.id,t.revision,request)).team.revision,stop.team.revision);await assert.rejects(()=>f.engine.start('owner',t.id,stop.team.revision),/halted/);await assert.rejects(()=>f.engine.resume('owner',t.id,stop.team.revision,{requestId:randomUUID(),reason:'继续'}),/Confirm every/);
 const unknown=await f.engine.reconcileStop('owner',t.id,stop.team.revision);assert.equal(unknown.team.executionControl.status,'stopping');assert.equal(unknown.team.executionControl.pending.length,2);for(const m of unknown.team.members)f.runs.set(m.rosterMarker,{threadId:m.agentThreadId,turnId:null,status:'starting',quiescence:{turnId:'init-'+m.id,status:'interrupted'},outputs:[],commands:[]});const halted=await f.engine.reconcileStop('owner',t.id,unknown.team.revision);assert.equal(halted.team.state,'halted');assert.deepEqual(halted.initializations,[]);await assert.rejects(()=>f.engine.resume('owner',t.id,halted.team.revision,{requestId:randomUUID(),reason:' '}),/reason/);const resumed=await f.engine.resume('owner',t.id,halted.team.revision,{requestId:randomUUID(),reason:'用户明确继续'});assert.equal(resumed.team.executionControl.status,'active');assert.equal(resumed.team.controlHistory.length,2);assert.ok(resumed.initializations.every(p=>p.action==='followup-native-member'));assert.ok(resumed.initializations.every(p=>p.threadId?.startsWith('child-')));for(const p of resumed.initializations){assert.ok(!t.members.some(m=>m.rosterMarker===p.marker));f.runs.set(p.marker,{threadId:p.threadId,turnId:'retry-'+p.memberId,status:'completed',outputs:[],commands:[]});const fresh=await f.saved();await f.engine.bindRoster('owner',fresh.id,fresh.revision,p.memberId,p.threadId);}assert.equal((await f.claim()).dispatch.action,'followup-native-member');});
test('stop retains failed attempt evidence; explicit retry preserves the role and consumes a clean execution attempt',async()=>{const f=await fixture(),c=await f.claim();f.run(c.dispatch);await f.bind(c.dispatch);let t=await f.saved();const stop=await f.engine.stop('owner',t.id,t.revision,{requestId:randomUUID(),reason:'修复前先停止'});f.run(c.dispatch,'interrupted',{quiescence:{turnId:'turn-'+c.dispatch.attemptId,status:'interrupted'}});const halted=await f.engine.reconcileStop('owner',t.id,stop.team.revision);assert.equal(halted.team.tasks[0].status,'blocked');assert.equal(halted.team.tasks[0].attempts[0].state,'stopped');const resumed=await f.engine.resume('owner',t.id,halted.team.revision,{requestId:randomUUID(),reason:'明确重试实现',retryTaskIds:['work']});const next=await f.engine.claim('owner',t.id,resumed.team.revision,'work');assert.equal(next.dispatch.action,'spawn-native-member');assert.equal(next.dispatch.existingThreadId,null);assert.equal(next.team.contextHistory[0].threadId,'child-dev');assert.notEqual(next.dispatch.attemptId,c.dispatch.attemptId);assert.equal(next.team.tasks[0].attempts.length,2);assert.equal(next.team.tasks[1].attempts.length,0);});
test('unbound reservations keep stopping until host verification and explicit release; read never mutates stop state',async()=>{const f=await fixture(),c=await f.claim(),stop=await f.engine.stop('owner',f.team.id,c.team.revision,{reason:'先核实派发',requestId:randomUUID()});const waiting=await f.engine.reconcileStop('owner',f.team.id,stop.team.revision);assert.equal(waiting.team.executionControl.status,'stopping');const before=await f.saved();await f.engine.read('owner',f.team.id);assert.deepEqual(await f.saved(),before);const released=await f.engine.release('owner',f.team.id,before.revision,'work',c.dispatch.attemptId,'核对宿主，成员尚未创建');const halted=await f.engine.reconcileStop('owner',f.team.id,released.team.revision);assert.equal(halted.team.state,'halted');assert.equal(halted.team.tasks[0].attempts[0].state,'released');});
test('contract amendments record before/after, invalidate downstream evidence, fence old readers and reject scope violations atomically',async()=>{const f=await fixture();let t=await f.saved();const input={taskId:'work',requestId:randomUUID(),reason:'补全遗漏的验收场景',patch:{acceptance:'增加边界输入验证',acceptanceCriteria:[{id:'edge',description:'边界输入正确'}]}};const amended=await f.engine.amendContract('owner',t.id,t.revision,input);assert.equal(amended.team.tasks[0].contractRevision,2);assert.equal(amended.team.contractAmendments[0].before.acceptance,'Verified behavior');assert.equal(amended.team.contractAmendments[0].after.acceptance,'增加边界输入验证');assert.equal(amended.team.dispatchPaused,true);assert.equal((await f.engine.amendContract('owner',t.id,t.revision,input)).team.contractAmendments.length,1);const bytes=await readFile(f.engine.store.document(t.id).v2,'utf8');await assert.rejects(()=>new OldArchive(f.engine.store.archive.root).hydrate(JSON.parse(bytes)),/Unsupported archive/);await assert.rejects(()=>f.engine.amendContract('owner',t.id,amended.team.revision,{...input,requestId:randomUUID(),patch:{contract:{stage:'implementation',inScope:['private'],outOfScope:[],verify:['node --test'],coverageOf:[]}}}),/write scope/);assert.equal((await f.saved()).tasks[0].contractRevision,2);});
test('running and previously accepted contracts cannot be weakened, and amendment does not reset attempt budgets',async()=>{const f=await fixture(),c=await f.claim(),input={taskId:'work',requestId:randomUUID(),reason:'修正目标',patch:{goal:'Updated scoped objective'}};await assert.rejects(()=>f.engine.amendContract('owner',f.team.id,c.team.revision,input),/Stop and settle/);await f.engine.store.update(f.team.id,'owner',c.team.revision,t=>{t.tasks[0].status='blocked';t.tasks[0].attempts[0].state='failed';t.tasks[0].attempts[0].review={decision:'accept'};t.members[0].status='idle';});const t=await f.saved();await assert.rejects(()=>f.engine.amendContract('owner',t.id,t.revision,input),/frozen/);assert.equal((await f.saved()).tasks[0].attempts.length,1);});
test('members can claim only their own assigned ready work, bind their real thread and report without accepting it',async()=>{const f=await fixture();let t=await f.saved();f.runs.set(t.members[0].rosterMarker,{threadId:'child-dev',turnId:'init-dev',status:'completed',outputs:[],commands:[]});await f.engine.bindRoster('owner',t.id,t.revision,'dev','child-dev');t=await f.saved();const input={taskId:'work',requestId:randomUUID()};await assert.rejects(()=>f.engine.memberClaim('owner',t.id,t.revision,{...f.ctx(),threadId:'foreign'},input),/authenticated/);await assert.rejects(()=>f.engine.memberClaim('owner',t.id,t.revision,f.ctx(),{...input,taskId:'review-work'}),/own assigned/);const c=await f.engine.memberClaim('owner',t.id,t.revision,f.ctx(),input);assert.equal(c.action,'continue-current-native-turn');assert.equal(c.existingThreadId,undefined);assert.equal((await f.engine.memberClaim('owner',t.id,t.revision,f.ctx(),input)).attemptId,c.attemptId);f.run({...c,memberId:'dev'});let bound=await f.engine.memberBind('owner',t.id,c.revision,f.ctx(),{taskId:'work',attemptId:c.attemptId});const report={taskId:'work',attemptId:c.attemptId,requestId:randomUUID(),summary:'实现完成，等待独立审查',decisions:[],remainingWork:['独立审查'],evidence:['src/result.mjs'],validation:[],delivery:c.marker+'\nImplemented scoped behavior'};const staged=await f.engine.memberReport('owner',t.id,bound.team.revision,f.ctx(),report);assert.equal(staged.checkpoint.source,'authenticated-member');assert.equal(staged.submissionStatus,'awaiting-native-terminal');t=await f.saved();assert.equal(t.tasks[0].status,'running');assert.equal(t.tasks[1].attempts.length,0);await assert.rejects(()=>f.engine.memberReport('owner',t.id,t.revision,f.ctx('qa'),report),/authenticated|own bound|your bound/);assert.equal(memberWork(t,f.ctx()).tasks.every(task=>task.taskId==='work'),true);f.run({...c,memberId:'dev'},'completed',{outputs:[{text:report.delivery}]});const settled=await f.engine.settle('owner',t.id,t.revision,'work',c.attemptId);assert.equal(settled.team.tasks[0].status,'submitted');assert.equal(settled.team.tasks[1].status,'waiting');});
test('roster-only profiles retain constraints without creating an empty DAG; seed profiles still require complete plans',async()=>{const root=await mkdtemp(join(tmpdir(),'dynamic-profile-')),profiles=new TeamProfiles(root),plan={members:[member('dev',['src']),member('qa')]};const p=await profiles.save('dynamic',plan,{tokenLimit:10000},'动态按任务规划',{taskPlanning:'leader',constraints:'必须独立审查，不扩大写范围'});assert.equal(p.taskPlanning,'leader');assert.equal(p.plan.tasks,undefined);assert.equal((await new TeamProfiles(root).read('dynamic')).constraints,p.constraints);await assert.rejects(()=>profiles.save('bad',plan),/plan needs|Plan needs/);await assert.rejects(()=>profiles.save('bad',{...plan,tasks:jobs('work')},{},'',{taskPlanning:'leader'}),/not a fixed DAG/);});
test('model catalog uses host-supported routes, deduplicates reads, rejects unavailable models/efforts and never starts a model turn',async()=>{const calls=[],catalog=new ModelCatalog({async connect(){return {async call(method,args){calls.push({method,args});return {data:[{model:'host-model',displayName:'Actual model',isDefault:true,defaultReasoningEffort:'medium',supportedReasoningEfforts:[{reasoningEffort:'low'},{reasoningEffort:'medium'}]},{model:'hidden-model',hidden:true}],nextCursor:null};}};}});const [a,b]=await Promise.all([catalog.read(),catalog.read()]);assert.deepEqual(a,b);assert.equal(calls.length,1);assert.equal(a.models.length,1);await catalog.validate([{route:{model:'host-model',reasoningEffort:'low'}}]);await assert.rejects(()=>catalog.validate([{route:{model:'host-model',reasoningEffort:'ultra'}}]),/does not support/);await assert.rejects(()=>catalog.validate([{route:{model:'invented'}}]),/not offered/);await assert.rejects(()=>catalog.validate([{route:{reasoningEffort:'low'}}]),/Select a host model/);assert.deepEqual(calls.map(c=>c.method),['model/list']);});
test('new stop and contract metadata remains bounded in state/panel; original histories stay accessible in full',async()=>{const f=await fixture(),t=await f.saved();await f.engine.amendContract('owner',t.id,t.revision,{taskId:'work',requestId:randomUUID(),reason:'补充说明',patch:{goal:'新的完整工作目标'}});const data=await f.engine.receipt('owner',t.id);for(const view of ['state','panel']){const p=teamResponse(data,view);assert.equal(p.team.memberStartup,'on-demand');assert.equal(JSON.stringify(p).includes('contractAmendments'),false);assert.ok(Buffer.byteLength(JSON.stringify(p))<256*1024);}assert.equal(teamResponse(data,'full').team.contractAmendments.length,1);});
test('concurrent stop requests deduplicate and a late replay after resume never interrupts new work',async()=>{const f=await fixture(),t=await f.saved(),input={requestId:randomUUID(),reason:'停止并核实'};const both=await Promise.all([f.engine.stop('owner',t.id,t.revision,input),f.engine.stop('owner',t.id,t.revision,input)]);assert.equal(both[0].team.revision,both[1].team.revision);const halted=await f.engine.reconcileStop('owner',t.id,both[0].team.revision),resume={requestId:randomUUID(),reason:'继续已授权任务'};const resumed=await Promise.all([f.engine.resume('owner',t.id,halted.team.revision,resume),f.engine.resume('owner',t.id,halted.team.revision,resume)]);assert.equal(resumed[0].team.revision,resumed[1].team.revision);const replay=await f.engine.stop('owner',t.id,t.revision,input);assert.equal(replay.leaderAction,null);assert.equal(replay.team.executionControl.status,'active');assert.equal(replay.team.controlHistory.length,2);});
test('catalog errors remain explicit and pagination cannot silently loop or fall back to invented routes',async()=>{const failed=new ModelCatalog({async connect(){return {async call(){throw new Error('Catalog offline');}};}});await assert.rejects(()=>failed.validate([{route:{model:'anything'}}]),/Catalog offline/);const loop=new ModelCatalog({async connect(){return {async call(){return {data:[],nextCursor:'same'};}};}});await assert.rejects(()=>loop.read(),/did not advance/);});

test('stop observation checks the latest native turn instead of mistaking an old completed initialization for idle',async()=>{
 const cwd=await realpath('.'),threadId='native-child',marker='TEAM_WORKSPACE_MEMBER:old',thread={id:threadId,cwd,parentThreadId:'leader'},turns=[{id:'init',status:'completed',items:[{type:'agentMessage',text:marker}]},{id:'latest-work',status:'inProgress',items:[]}];let aborted=false;
 const observer=new NativeMembers({rpcFactory:()=>({async connect(){},async call(method,p){assert.equal(method,'thread/read');return {thread:{...thread,...(p.includeTurns?{turns}:{})}};},async close(){}}),lifecycleReader:async()=>({status:aborted?'interrupted':'unknown'}),publicFeed:{async read(){return {events:[],usage:null};}}});
 try{await assert.rejects(()=>observer.inspect('leader',cwd,threadId,marker,{allowPending:true,requireIdle:true}),/not confirmed idle/);turns[1].status='interrupted';await assert.rejects(()=>observer.inspect('leader',cwd,threadId,marker,{allowPending:true,requireIdle:true}),/not confirmed idle/);aborted=true;const observed=await observer.inspect('leader',cwd,threadId,'new-marker-with-no-ack',{allowPending:true,requireIdle:true});assert.equal(observed.turnId,null);assert.deepEqual(observed.quiescence,{turnId:'latest-work',status:'interrupted',source:'native-latest-turn'});}finally{await observer.close();}
});
