import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {LeaderEngine} from '../src/leader-engine.mjs';
import {teamResponse} from '../src/team-responses.mjs';

async function fixture({failRead=false,failMessage=false}={}){
 const root=await mkdtemp(join(tmpdir(),'plan-review-ui-')),engine=new LeaderEngine({root}),team=await engine.planOnce('owner',{cwd:root,threadId:'leader'},{goal:'完善项目引用目录的插入与焦点恢复',execute:true,approvalMode:'required',initializeMembers:true,plan:{members:[{id:'dev',role:'开发工程师',responsibility:'实现目录搜索和插入',reason:'完成用户需求',writeScopes:['src']},{id:'qa',role:'独立审查工程师',responsibility:'验证插入和焦点恢复',reason:'独立验收',writeScopes:[]}],tasks:[{id:'work',title:'修复引用目录',goal:'保存原输入位置',acceptance:'搜索后可插入文本中间',memberId:'dev',priority:3,kind:'work',dependencies:[]},{id:'review',title:'独立验证',goal:'检查引用行为',acceptance:'验证插入和焦点恢复',memberId:'qa',priority:3,kind:'review',reviewOfTaskId:'work',dependencies:[{taskId:'work',when:'submitted'}]}]}});
 const html=(await readFile('src/host.html','utf8')).replace('<script>/*__BUNDLE__*/</script>',''),server=createServer(async(req,res)=>{if(!['/','/team-view.mjs','/team-projection.mjs','/team-naming.mjs'].includes(req.url)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',req.url==='/'?'text/html':'text/javascript');res.end(req.url==='/'?html:await readFile('src'+req.url,'utf8'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1040,height:900}}),errors=[],calls=[],messages=[];page.on('pageerror',e=>errors.push(e.message));
 const state=async(view='state')=>teamResponse(await engine.receipt('owner',team.id),view);
 await page.exposeFunction('teamTool',async({name,arguments:a})=>{calls.push(name);try{let data;if(name==='read_team_plan'){if(failRead){failRead=false;throw new Error('Controlled connection failure');}data=await engine.readPlan('owner',team.id);}else if(name==='read_team')data=await state(a.view);else if(name==='revise_team_plan')data=await engine.revisePlan('owner',team.id,a.revision,a.configuration,a.brief);else if(name==='approve_team_plan'||name==='cancel_team_plan')data=teamResponse(await engine.decidePlan('owner',team.id,a.revision,a,name==='approve_team_plan'?'approve':'cancel'));else throw new Error('Unexpected '+name);return {structuredContent:data};}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}});
 await page.exposeFunction('sendLeaderMessage',async(message)=>{assert.equal((await engine.store.get(team.id,'owner')).planReview.status,'approved');messages.push(message);if(failMessage)throw new Error('Controlled message failure');return {};});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(async data=>{const {setupTeamView}=await import('/team-view.mjs');window.view=setupTeamView({callServerTool:window.teamTool,getHostCapabilities:()=>({message:{}}),sendMessage:window.sendLeaderMessage});await window.view.accept(data);},await state('panel'));
 return {engine,team,page,calls,messages,errors,state,async close(){await page.evaluate(()=>window.view.close());await browser.close();await new Promise(r=>server.close(r));}};
}
test('review UI edits the complete plan, keeps drafts across refresh, saves a new version, confirms and then notifies Leader',async()=>{const f=await fixture();try{
 await expect(f.page.locator('#planReviewStatus')).toContainText('第 1 版 · 等待确认');await expect(f.page.locator('#planApprove')).toBeEnabled();await expect(f.page.getByLabel('任务目标',{exact:true})).toHaveValue('完善项目引用目录的插入与焦点恢复');
 await f.page.getByLabel('任务目标',{exact:true}).fill('完善引用目录并增加独立的异常输入验证');await expect(f.page.locator('#planApprove')).toBeDisabled();
 await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(f.page.getByLabel('任务目标',{exact:true})).toHaveValue('完善引用目录并增加独立的异常输入验证');
 await f.page.locator('#planSave').click();await expect(f.page.locator('#planReviewStatus')).toContainText('第 2 版');await expect(f.page.locator('#planApprove')).toBeEnabled();const saved=await f.engine.store.get(f.team.id,'owner');assert.equal(saved.planHistory.length,2);assert.ok(saved.members.every(m=>!m.agentThreadId));
 await mkdir('evidence/plan-review-ui',{recursive:true});await f.page.screenshot({path:'evidence/plan-review-ui/wide.png',fullPage:true});await f.page.setViewportSize({width:360,height:900});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await f.page.screenshot({path:'evidence/plan-review-ui/narrow.png'});
 await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewStatus')).toContainText('已确认');await expect(f.page.locator('#planReviewFeedback')).toContainText('已通知主会话');assert.equal(f.messages.length,1);assert.equal(f.calls.filter(n=>n==='approve_team_plan').length,1);assert.match(f.messages[0].content[0].text,/planVersion=2/);const approved=await f.engine.store.get(f.team.id,'owner');assert.equal(approved.planReview.approval.source,'panel-user-action');assert.ok(approved.tasks.every(t=>t.status==='waiting'));assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('failed plan reads remain bounded and retryable; confirmed plans survive failed Leader notification',async()=>{const f=await fixture({failRead:true,failMessage:true});try{
 await expect(f.page.locator('#planReviewFeedback')).toContainText('Controlled connection failure');assert.equal(f.calls.filter(n=>n==='read_team_plan').length,1);await expect(f.page.locator('#planApprove')).toBeDisabled();await f.page.locator('#planReload').click();await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewFeedback')).toContainText('计划已确认。请回到主会话');assert.equal((await f.engine.store.get(f.team.id,'owner')).planReview.status,'approved');assert.equal(f.calls.filter(n=>n==='approve_team_plan').length,1);assert.equal(f.messages.length,1);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('cancel button preserves the unstarted draft with no model or Leader message',async()=>{const f=await fixture();try{await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planCancel').click();await expect(f.page.locator('#planReviewStatus')).toContainText('已取消');const team=await f.engine.store.get(f.team.id,'owner');assert.equal(team.state,'cancelled');assert.ok(team.members.every(m=>!m.agentThreadId));assert.equal(f.messages.length,0);assert.deepEqual(f.errors,[]);}finally{await f.close();}});
