import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {LeaderEngine} from '../src/leader-engine.mjs';
import {teamResponse} from '../src/team-responses.mjs';

async function fixture({failRead=false,failMessage=false,delayStopPanel=false,memberStartup='eager'}={}){
 let releaseStopPanel;const stopPanel=new Promise(resolve=>{releaseStopPanel=resolve;});
 const runs=new Map(),observer={async inspect(l,p,id,marker,options={}){const run=runs.get(marker);if(!run||run.threadId!==id||options.requireIdle&&!run.quiescence)throw new Error('Native terminal record unavailable');return structuredClone(run);}};
 const root=await mkdtemp(join(tmpdir(),'plan-review-ui-')),engine=new LeaderEngine({root,observer}),team=await engine.planOnce('owner',{cwd:root,threadId:'leader'},{goal:'完善项目引用目录的插入与焦点恢复',execute:true,approvalMode:'required',initializeMembers:true,memberStartup,plan:{members:[{id:'dev',role:'开发工程师',responsibility:'实现目录搜索和插入',reason:'完成用户需求',writeScopes:['src']},{id:'qa',role:'独立审查工程师',responsibility:'验证插入和焦点恢复',reason:'独立验收',writeScopes:[]}],tasks:[{id:'work',title:'修复引用目录',goal:'保存原输入位置',acceptance:'搜索后可插入文本中间',memberId:'dev',priority:3,kind:'work',dependencies:[]},{id:'review',title:'独立验证',goal:'检查引用行为',acceptance:'验证插入和焦点恢复',memberId:'qa',priority:3,kind:'review',reviewOfTaskId:'work',dependencies:[{taskId:'work',when:'submitted'}]}]}});
 const html=(await readFile('src/host.html','utf8')).replace('<script>/*__BUNDLE__*/</script>',''),server=createServer(async(req,res)=>{if(!['/','/team-view.mjs','/team-projection.mjs','/team-naming.mjs'].includes(req.url)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',req.url==='/'?'text/html':'text/javascript');res.end(req.url==='/'?html:await readFile('src'+req.url,'utf8'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1040,height:900}}),errors=[],calls=[],messages=[];page.on('pageerror',e=>errors.push(e.message));
 const state=async(view='state')=>teamResponse(await engine.receipt('owner',team.id),view);
 await page.exposeFunction('teamTool',async({name,arguments:a})=>{calls.push(name);try{let data;if(name==='read_team_plan'){if(failRead){failRead=false;throw new Error('Controlled connection failure');}data=await engine.readPlan('owner',team.id);}else if(name==='read_team'){data=await state(a.view);if(delayStopPanel&&a.view==='panel'&&data.team.executionControl?.status==='stopping')await stopPanel;}else if(name==='read_team_model_catalog')data={models:[{model:'host-a',displayName:'Host A',supportedReasoningEfforts:['low','medium']},{model:'host-b',displayName:'Host B',supportedReasoningEfforts:['low']}]};else if(name==='stop_team')data=teamResponse(await engine.stop('owner',team.id,a.revision,a));else if(name==='resume_team')data=teamResponse(await engine.resume('owner',team.id,a.revision,a));else if(name==='revise_team_plan')data=await engine.revisePlan('owner',team.id,a.revision,a.configuration,a.brief);else if(name==='approve_team_plan'||name==='cancel_team_plan')data=teamResponse(await engine.decidePlan('owner',team.id,a.revision,a,name==='approve_team_plan'?'approve':'cancel'));else throw new Error('Unexpected '+name);return {structuredContent:data};}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}});
 await page.exposeFunction('sendLeaderMessage',async(message)=>{assert.equal((await engine.store.get(team.id,'owner')).planReview.status,'approved');messages.push(message);if(failMessage)throw new Error('Controlled message failure');return {};});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(async data=>{const {setupTeamView}=await import('/team-view.mjs');window.view=setupTeamView({callServerTool:window.teamTool,getHostCapabilities:()=>({message:{}}),sendMessage:window.sendLeaderMessage});await window.view.accept(data);},await state('panel'));
 return {engine,team,runs,page,calls,messages,errors,state,releaseStopPanel,async close(){releaseStopPanel();await page.evaluate(()=>window.view.close());await browser.close();await new Promise(r=>server.close(r));}};
}
test('review UI edits the complete plan, keeps drafts across refresh, saves a new version, confirms and then notifies Leader',async()=>{const f=await fixture();try{
 await expect(f.page.locator('#planReviewStatus')).toContainText('第 1 版 · 等待确认');await expect(f.page.locator('#planApprove')).toBeEnabled();await expect(f.page.getByLabel('任务目标',{exact:true})).toHaveValue('完善项目引用目录的插入与焦点恢复');
 await f.page.getByLabel('任务目标',{exact:true}).fill('完善引用目录并增加独立的异常输入验证');await expect(f.page.locator('#planApprove')).toBeDisabled();
 await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(f.page.getByLabel('任务目标',{exact:true})).toHaveValue('完善引用目录并增加独立的异常输入验证');
 await f.page.locator('#planSave').click();await expect(f.page.locator('#planReviewStatus')).toContainText('第 2 版');await expect(f.page.locator('#planApprove')).toBeEnabled();const saved=await f.engine.store.get(f.team.id,'owner');assert.equal(saved.planHistory.length,2);assert.ok(saved.members.every(m=>!m.agentThreadId));
 await mkdir('evidence/plan-review-ui',{recursive:true});await f.page.screenshot({path:'evidence/plan-review-ui/wide.png',fullPage:true});await f.page.setViewportSize({width:360,height:900});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await f.page.screenshot({path:'evidence/plan-review-ui/narrow.png'});
 await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewStatus')).toContainText('已确认');await expect(f.page.locator('#planReviewFeedback')).toContainText('已通知主会话');assert.equal(f.messages.length,1);assert.equal(f.calls.filter(n=>n==='approve_team_plan').length,1);assert.match(f.messages[0].content[0].text,/planVersion=2/);const approved=await f.engine.store.get(f.team.id,'owner');assert.equal(approved.planReview.approval.source,'panel-user-action');assert.ok(approved.tasks.every(t=>t.status==='waiting'));assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('failed plan reads remain bounded and retryable; confirmed plans survive failed Leader notification',async()=>{const f=await fixture({failRead:true,failMessage:true});try{
 await expect(f.page.locator('#planReviewFeedback')).toContainText('Controlled connection failure');assert.equal(f.calls.filter(n=>n==='read_team_plan').length,1);await expect(f.page.locator('#planApprove')).toBeDisabled();await f.page.locator('#planReload').click();await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewFeedback')).toContainText('计划已确认。请回到主会话');assert.equal((await f.engine.store.get(f.team.id,'owner')).planReview.status,'approved');assert.equal(f.calls.filter(n=>n==='approve_team_plan').length,1);assert.equal(f.messages.length,1);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('cancel button preserves the unstarted draft with no model or Leader message',async()=>{const f=await fixture();try{await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planCancel').click();await expect(f.page.locator('#planReviewStatus')).toContainText('已取消');const team=await f.engine.store.get(f.team.id,'owner');assert.equal(team.state,'cancelled');assert.ok(team.members.every(m=>!m.agentThreadId));assert.equal(f.messages.length,0);assert.deepEqual(f.errors,[]);}finally{await f.close();}});

test('plan forms add/remove roles and reviewed deliveries, choose validated model options, edit dependencies and budgets without JSON',async()=>{const f=await fixture();try{
 await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planAddMember').click();const roleId=await f.page.locator('#planReviewContent [data-member-id]').last().getAttribute('data-member-id');await f.page.getByLabel('岗位 '+roleId,{exact:true}).fill('文档工程师');await f.page.getByLabel('职责 '+roleId,{exact:true}).fill('解释目录搜索和插入行为');await f.page.getByLabel('设置理由 '+roleId,{exact:true}).fill('完善交付文档');await f.page.getByLabel('写入范围 '+roleId,{exact:true}).fill('docs');
 await f.page.locator('#planLoadModels').click();await expect(f.page.getByLabel('模型 dev',{exact:true})).toBeEnabled();await f.page.getByLabel('模型 dev',{exact:true}).selectOption('host-a');await f.page.getByLabel('思考档位 dev',{exact:true}).selectOption('medium');assert.equal(await f.page.getByLabel('思考档位 dev',{exact:true}).locator('option').count(),3);await f.page.getByLabel('模型 dev',{exact:true}).selectOption('host-b');await expect(f.page.getByLabel('思考档位 dev',{exact:true})).toHaveValue('');assert.equal(await f.page.getByLabel('思考档位 dev',{exact:true}).locator('option').count(),2);await f.page.getByLabel('思考档位 dev',{exact:true}).selectOption('low');
 await f.page.locator('#planAddTask').click();const workId=await f.page.locator('#planReviewContent [data-task-id]').nth(2).getAttribute('data-task-id');await f.page.getByLabel('任务名称 '+workId,{exact:true}).fill('边界输入回归');await f.page.getByLabel('任务目标 '+workId,{exact:true}).fill('验证特殊字符搜索');await f.page.getByLabel('验收条件 '+workId,{exact:true}).fill('特殊字符不破坏插入位置');await f.page.getByLabel('负责岗位 '+workId,{exact:true}).selectOption(roleId);
 const deps=f.page.getByLabel('依赖 '+workId+' ← work',{exact:true});await deps.locator('..').locator('..').locator('summary').click();await deps.selectOption('accepted');await f.page.getByText('并发与执行预算',{exact:true}).click();await f.page.getByLabel('最大并发',{exact:true}).fill('2');await f.page.getByLabel('Token 上限（留空表示不限）',{exact:true}).fill('15000');await f.page.getByLabel('每项任务最大尝试次数',{exact:true}).fill('4');await f.page.getByLabel('成员启动方式',{exact:true}).selectOption('on-demand');
 await f.page.locator('#planSave').click();await expect(f.page.locator('#planReviewFeedback')).toContainText('修改已保存');await expect(f.page.locator('#planReviewStatus')).toContainText('第 2 版');let t=await f.engine.store.get(f.team.id,'owner');assert.equal(t.members.length,3);assert.equal(t.tasks.length,4);assert.equal(t.tasks.find(t=>t.id===workId).memberId,roleId);assert.deepEqual(t.tasks.find(t=>t.id===workId).dependencies,[{taskId:'work',when:'accepted'}]);assert.deepEqual(t.members[0].route,{model:'host-b',reasoningEffort:'low'});assert.equal(t.policy.tokenLimit,15000);assert.equal(t.policy.maxAttempts,4);assert.equal(t.memberStartup,'on-demand');
 await f.page.getByRole('button',{name:'删除任务 '+workId,exact:true}).click();await f.page.getByRole('button',{name:'删除岗位 '+roleId,exact:true}).click();await f.page.locator('#planSave').click();await expect(f.page.locator('#planReviewStatus')).toContainText('第 3 版');t=await f.engine.store.get(f.team.id,'owner');assert.equal(t.members.length,2);assert.equal(t.tasks.length,2);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
test('one-click stop/resume records default reasons and waits for native terminal verification',async()=>{const f=await fixture();try{
 await expect(f.page.locator('#teamControl')).toBeHidden();await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewBody')).toBeHidden();await expect(f.page.locator('#teamControlReason')).toBeHidden();await f.page.locator('#teamStop').click();
 await expect(f.page.locator('#teamControlStatus')).toContainText('正在停止');await expect(f.page.locator('#teamResume')).toBeHidden();await expect(f.page.locator('#teamControlOptions')).toBeHidden();let t=await f.engine.store.get(f.team.id,'owner');assert.equal(t.executionControl.status,'stopping');assert.equal(t.controlHistory[0].reason,'用户在团队面板点击停止');assert.equal(f.calls.filter(n=>n==='stop_team').length,1);assert.ok(f.messages.at(-1).content[0].text.includes('包括初始化'));
 await f.engine.reconcileStop('owner',t.id,t.revision);await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(f.page.locator('#teamControlStatus')).toContainText('团队已停止');await expect(f.page.locator('#teamControlFeedback')).toContainText('已保留');await f.page.locator('#teamResume').click();await expect(f.page.locator('#teamControlStatus')).toHaveText('等待执行');t=await f.engine.store.get(f.team.id,'owner');assert.equal(t.executionControl.status,'active');assert.equal(t.controlHistory.length,2);assert.equal(t.controlHistory[1].reason,'用户在团队面板点击继续执行');assert.ok(t.tasks.every(t=>t.status==='waiting'));assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});

test('optional notes survive refresh and language changes; failed notification preserves the stop without resubmitting',async()=>{const f=await fixture({failMessage:true,delayStopPanel:true});try{
 await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();await f.page.locator('#teamControlOptionsLabel').click();await f.page.getByLabel('操作说明（可选）',{exact:true}).fill('检查当前交付再继续');await f.page.evaluate(data=>window.view.accept(data),await f.state());await f.page.locator('#teamLocale').selectOption('en');await expect(f.page.getByLabel('Note (optional)',{exact:true})).toHaveValue('检查当前交付再继续');await expect(f.page.locator('#teamStop')).toHaveText('Stop');await f.page.locator('#teamLocale').selectOption('zh-CN');
 await f.page.locator('#teamStop').press('Enter');await expect(f.page.locator('#teamControlFeedback')).toContainText('停止请求已保存；通知失败');let t=await f.engine.native('owner',f.team.id);assert.equal(t.executionControl.status,'stopping');assert.equal(t.controlHistory[0].reason,'检查当前交付再继续');f.releaseStopPanel();await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(f.page.locator('#teamControlFeedback')).toContainText('停止请求已保存；通知失败');await f.page.locator('#teamLocale').selectOption('en');await expect(f.page.locator('#teamControlFeedback')).toContainText('Stop request saved');await f.page.locator('#teamLocale').selectOption('zh-CN');assert.equal(f.calls.filter(n=>n==='stop_team').length,1);await expect(f.page.locator('#teamResume')).toBeHidden();await f.page.setViewportSize({width:360,height:900});assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});

test('settled plans open on demand; management drafts remain available after closing and refresh',async()=>{const f=await fixture();try{
 await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();assert.equal(f.calls.filter(n=>n==='read_team_plan').length,1);await expect(f.page.locator('#planReviewBody')).toBeHidden();await expect(f.page.locator('#teamAutoAdvance')).toBeHidden();await f.page.locator('#planSummaryToggle').click();await expect(f.page.locator('#planReviewBody')).toBeVisible();await expect(f.page.getByLabel('任务目标',{exact:true})).toBeDisabled();await f.page.locator('#planSummaryToggle').click();await expect(f.page.locator('#planReviewBody')).toBeHidden();
 await f.page.locator('#teamManageOpen').click();await f.page.getByLabel('操作原因',{exact:true}).fill('保留尚未保存的调整');await f.page.locator('#teamManagementClose').click();await expect(f.page.locator('#teamManagementPanel')).toBeHidden();await expect(f.page.locator('#teamManageOpen')).toBeFocused();await f.page.evaluate(data=>window.view.accept(data),await f.state());await f.page.locator('#teamManageOpen').click();await expect(f.page.getByLabel('操作原因',{exact:true})).toHaveValue('保留尚未保存的调整');await f.page.locator('#teamManageOpen').click();await expect(f.page.locator('#teamManagementPanel')).toBeHidden();assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});

test('resume defaults only stopped attempts, keeps explicit deselection, and never implicitly retries failed work',async()=>{const f=await fixture({memberStartup:'on-demand'});try{
 await expect(f.page.locator('#planApprove')).toBeEnabled();await f.page.locator('#planApprove').click();await expect(f.page.locator('#planReviewStatus')).toContainText('已确认');let t=await f.engine.native('owner',f.team.id);const c=await f.engine.claim('owner',t.id,t.revision,'work'),p=c.dispatch,run={threadId:'native-dev',turnId:'turn-work',status:'inProgress',outputs:[],commands:[]};f.runs.set(p.marker,run);await f.engine.bind('owner',t.id,c.team.revision,'work',p.attemptId,run.threadId);await f.page.evaluate(data=>window.view.accept(data),await f.state());await f.page.locator('#teamStop').click();await expect(f.page.locator('#teamControlStatus')).toHaveText('正在停止');
 f.runs.set(p.marker,{...run,status:'interrupted',quiescence:{turnId:run.turnId,status:'interrupted'}});t=await f.engine.native('owner',f.team.id);await f.engine.reconcileStop('owner',t.id,t.revision);await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(f.page.locator('#teamControlHint')).toContainText('1 项任务将重试');await f.page.locator('#teamControlOptionsLabel').click();const retry=f.page.locator('#teamRetryTasks input[value=work]');await expect(retry).toBeChecked();await retry.uncheck();await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(retry).not.toBeChecked();
 t=await f.engine.native('owner',f.team.id);await f.engine.store.update(t.id,'owner',t.revision,t=>{t.tasks[0].attempts.at(-1).state='failed';});await f.page.evaluate(data=>window.view.accept(data),await f.state());await expect(retry).not.toBeChecked();await f.page.locator('#teamResume').click();await expect(f.page.locator('#teamControlStatus')).toHaveText('等待执行');t=await f.engine.native('owner',f.team.id);assert.equal(t.tasks[0].status,'blocked');assert.equal(t.tasks[0].attempts.length,1);assert.equal(t.controlHistory.length,2);assert.deepEqual(f.errors,[]);
 }finally{await f.close();}});
