import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {LeaderEngine} from '../src/leader-engine.mjs';
import {validateTeam} from '../src/team.mjs';
import {TeamCoordination} from '../src/team-coordination.mjs';
import {planHash} from '../src/team-plan-review.mjs';
const members=[{id:'dev',role:'开发',responsibility:'实现已确认目标',reason:'交付',writeScopes:['src']},{id:'qa',role:'审查',responsibility:'独立验证交付',reason:'验收',writeScopes:[]}];
const tasks=[{id:'work',title:'实现',goal:'实现已确认范围的功能',acceptance:'行为验证通过',memberId:'dev',priority:3,kind:'work',dependencies:[]},{id:'review',title:'独立审查',goal:'检查实现和测试',acceptance:'提供真实证据',memberId:'qa',priority:3,kind:'review',reviewOfTaskId:'work',dependencies:[{taskId:'work',when:'submitted'}]}];
async function fixture(options={}){const root=await mkdtemp(join(tmpdir(),'team-formation-')),observer={async inspect(){throw new Error('No native session should be read during formation');}},engine=new LeaderEngine({root,observer});const team=await engine.planOnce('owner',{cwd:root,threadId:'leader'},{goal:'完成当前项目已经明确的功能目标',taskPlanning:'leader',execute:true,approvalMode:'auto',initializeMembers:true,memberStartup:'on-demand',plan:{members:structuredClone(members),tasks:[]},...options});return {root,engine,team,saved:()=>engine.native('owner',team.id),approve:async()=>{const t=await engine.native('owner',team.id);return engine.decidePlan('owner',t.id,t.revision,{planVersion:t.planReview.version,planHash:t.planReview.hash,requestId:randomUUID(),note:'确认团队成员和目标'},'approve');}};}
test('new team confirms only the goal and members, then the Leader plans independently reviewed tasks without another approval',async()=>{
 const f=await fixture(),draft=await f.engine.readPlan('owner',f.team.id),pending=await f.engine.read('owner',f.team.id);assert.equal(draft.review.status,'pending');assert.equal(draft.review.confirmation,'team');assert.equal(draft.configuration.taskPlanning,'leader');assert.equal('tasks' in draft.configuration.plan,false);assert.deepEqual(pending.initializations,[]);assert.equal(pending.workflow.actions[0].type,'plan-review');
 await assert.rejects(()=>f.engine.addTasks('owner',f.team.id,f.team.revision,tasks),/unapproved/);
 const approved=await f.approve();assert.equal(approved.workflow.stage,'task-planning');assert.equal(approved.workflow.actions[0].type,'plan-tasks');assert.equal(approved.workflow.actions[0].requiresUserConfirmation,false);assert.equal(approved.workflow.actions.some(a=>a.type==='final-validation'),false);assert.deepEqual(approved.initializations,[]);
 const before=approved.team.planReview;const added=await f.engine.addTasks('owner',f.team.id,approved.team.revision,tasks);assert.deepEqual(added.team.planReview,before);assert.equal(added.team.planHistory.length,1);assert.equal(added.workflow.stage,'execute');assert.ok(added.workflow.actions.some(a=>a.type==='claim-batch'));assert.equal((await f.engine.readPlan('owner',f.team.id)).review.hash,draft.review.hash);const packet=await f.engine.claim('owner',f.team.id,added.team.revision,'work');assert.ok(packet.dispatch);assert.equal(packet.dispatch.action,'spawn-native-member');
});
test('taskless approved teams cannot finish or dispatch invented work, and stop/resume retains the planning stage',async()=>{
 const f=await fixture();let t=(await f.approve()).team;await assert.rejects(()=>f.engine.finish('owner',t.id,t.revision,'完成',[{name:'checks',status:'PASS',evidence:'controlled check'}]),/concrete deliveries/);await assert.rejects(()=>f.engine.addTasks('owner',t.id,t.revision,[]),/concrete tasks/);await assert.rejects(()=>f.engine.addTasks('owner',t.id,t.revision,[tasks[0]]),/independent review/);assert.deepEqual((await f.saved()).tasks,[]);
 await f.engine.stop('owner',t.id,t.revision,{requestId:randomUUID(),reason:'人工暂停'});t=await f.saved();await f.engine.reconcileStop('owner',t.id,t.revision);t=await f.saved();assert.deepEqual((await f.engine.read('owner',t.id)).workflow.actions,[]);const resumed=await f.engine.resume('owner',t.id,t.revision,{requestId:randomUUID(),reason:'继续拆分任务',retryTaskIds:[]});assert.equal(resumed.workflow.stage,'task-planning');assert.equal(resumed.workflow.actions[0].type,'plan-tasks');
});
test('formation edits invalidate old confirmations, reject embedded tasks and preserve a roster-only approval snapshot',async()=>{
 const f=await fixture(),draft=await f.engine.readPlan('owner',f.team.id),configuration=structuredClone(draft.configuration);configuration.goal='完成新调整后的项目功能目标';configuration.plan.members[0].responsibility='实现调整后的交付';await f.engine.revisePlan('owner',f.team.id,f.team.revision,configuration);let t=await f.saved();assert.equal(t.planReview.version,2);assert.notEqual(t.planReview.hash,draft.review.hash);await assert.rejects(()=>f.engine.decidePlan('owner',t.id,t.revision,{planVersion:1,planHash:draft.review.hash,requestId:randomUUID(),note:'旧版确认'},'approve'),/version changed/);
 const invalid={...configuration,plan:{...configuration.plan,tasks}};await assert.rejects(()=>f.engine.revisePlan('owner',t.id,t.revision,invalid),/formation does not confirm/);assert.equal((await f.saved()).revision,t.revision);assert.equal(planHash((await f.engine.readPlan('owner',t.id)).configuration),t.planReview.hash);t.requiresTeamWorkspaceVersion='0.17.0';assert.throws(()=>validateTeam(t),/formation requires/);
});
test('formation workflow uses native internal coordination with no panel chat offer',async()=>{
 const f=await fixture(),data=await f.approve(),coordination=new TeamCoordination(f.root);assert.equal((await coordination.reserve('owner',data)).firstOffer,false);assert.equal(data.workflow.communication.chatMessages,false);assert.equal(data.workflow.communication.waitTool,'wait_team_event');assert.equal(data.workflow.actions[0].requiresUserConfirmation,false);
 const added=await f.engine.addTasks('owner',f.team.id,data.team.revision,tasks);assert.equal(added.workflow.actions.some(a=>a.type==='plan-tasks'),false);assert.equal((await coordination.reserve('owner',added)).firstOffer,false);
});
test('pending legacy plans can switch to formation-only while retaining the original task plan in history',async()=>{
 const f=await fixture({taskPlanning:undefined,approvalMode:'required',plan:{members:structuredClone(members),tasks:structuredClone(tasks)}}),draft=await f.engine.readPlan('owner',f.team.id);const configuration={...draft.configuration,taskPlanning:'leader',plan:{...draft.configuration.plan,tasks:[]}};await f.engine.revisePlan('owner',f.team.id,f.team.revision,configuration);const t=await f.saved();assert.equal(t.requiresTeamWorkspaceVersion,'0.18.0');assert.equal(t.planReview.confirmation,'team');assert.equal(t.planHistory[0].configuration.plan.tasks.length,2);assert.equal('tasks' in t.planHistory[1].configuration.plan,false);assert.deepEqual(t.tasks,[]);assert.equal((await f.approve()).workflow.actions[0].type,'plan-tasks');
});
test('formation honors explicit direct execution and material expansions still require confirmation',async()=>{
 const f=await fixture({approvalMode:'immediate',executionAuthorization:'用户明确要求直接执行当前目标'}),t=await f.saved();assert.equal(t.planReview.status,'approved');assert.equal((await f.engine.read('owner',t.id)).workflow.actions[0].type,'plan-tasks');const changed=await f.engine.addTasks('owner',t.id,t.revision,tasks,{scopeChange:true,note:'用户提出新的范围'});assert.equal(changed.team.planReview.status,'pending');assert.equal(changed.team.planReview.scope,'expansion');assert.deepEqual(changed.team.tasks,[]);assert.equal(changed.workflow.actions.some(a=>a.type==='plan-tasks'),false);
});
