import {readTeamSource,prepareTeamCommand,readTeamCommandLog} from './team-output.mjs';
import {SchemaCatalog,peerReceipt,efficiencyAdvice} from './team-efficiency.mjs';
import {coordinationResponse} from './team-coordination-response.mjs';
import {waitTeamEvent} from './team-events.mjs';
import {TeamCoordination} from './team-coordination.mjs';
import {ModelCatalog} from './model-catalog.mjs';
import {memberWork} from './member-work.mjs';
import {assertPlanExecutable,assertPlanMutable} from './team-plan-review.mjs';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { registerAppResource, registerAppTool as registerSdkTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import {AsyncLocalStorage} from 'node:async_hooks';
import { z } from 'zod';
import { PrototypeRuntime } from './runtime.mjs';
import {HostContext,authorizeTeam} from './host-context.mjs';
import {TeamEngine} from './team-engine.mjs';
import {LeaderEngine} from './leader-engine.mjs';
import {ProjectTeams} from './project-teams.mjs';
import {TeamNavigation} from './team-navigation.mjs';
import {memberGoalDetail} from './member-goals.mjs';
import {requireTeamVersion} from './team-version.mjs';
import {teamResponse,advancementResponse,operationResponse} from './team-responses.mjs';
import {evidencePage} from './team-evidence.mjs';
import {RequestContext} from './request-context.mjs';
import {PanelSnapshot} from './panel-snapshot.mjs';
import {TeamProfiles,normalizePolicy,compactHandoff} from './team-policy.mjs';
import {taskQuery,exportTeam} from './team-diagnostics.mjs';
import {recoveryPacket,recordRecoveryControl,takeoverBoundary} from './team-recovery.mjs';
import {queuePeerMessage,peerInbox,pendingPeerInbox,peerMessagePage,acknowledgePeerMessage,recordPeerDelivery} from './team-peer-mailbox.mjs';
import {TeamWorktrees} from './team-worktrees.mjs';
import packageInfo from '../package.json' with {type:'json'};

const operationHandlers=new Map();
const responseContext=new AsyncLocalStorage();
const memberOperations=new Set(['read_member_team_work','claim_member_team_task','bind_member_team_task','report_member_team_task','send_team_peer_message','read_team_inbox','acknowledge_team_peer_message','read_team_context','record_team_peer_sender_delivery','read_team_source','prepare_team_command','read_team_command_log','consume_team_inbox','read_team_peer_message']);
const sharedOperations=new Set(['read_team_context','read_team_source','prepare_team_command','read_team_command_log','consume_team_inbox','read_team_peer_message']);
const debugOperation=name=>/probe|stop_trial/.test(name);
const compactTools=new Set(['open_team_workspace','get_current_project','read_team','team_command','team_leader','team_member']);
function registerAppTool(target,name,options,handler){
  operationHandlers.set(name,{options,handler});
  const metadata={...options._meta,ui:{...options._meta?.ui,...(!compactTools.has(name)?{visibility:['app']}:{})}};
  return registerSdkTool(target,name,{...options,_meta:metadata},compactTools.has(name)?(...args)=>responseContext.run({...responseContext.getStore(),singleCopy:true},()=>handler(...args)):handler);
}
const VERSION = packageInfo.version;
const schemaCatalog=new SchemaCatalog(VERSION);
const URI = `ui://team-workspace-probe/${VERSION}/host.html`;
const bootId = randomUUID();
const startedAt = new Date().toISOString();
const server = new McpServer({ name: 'team-workspace-probe', version: VERSION });
const runtime = new PrototypeRuntime();
const engine=new TeamEngine({root:process.env.TEAM_WORKSPACE_DATA_ROOT});
const leader=new LeaderEngine({root:process.env.TEAM_WORKSPACE_DATA_ROOT,store:engine.store});
const projectTeams=new ProjectTeams(leader);
const navigation=new TeamNavigation({root:leader.root,store:engine.store,observer:leader.observer});
const panelSnapshot=new PanelSnapshot();
const profiles=new TeamProfiles(leader.root);
const coordination=new TeamCoordination(leader.root);
const worktrees=new TeamWorktrees(join(leader.root,'worktrees'));
const readTeam=async(o,id)=>(await engine.store.get(id,o)).mode==='host-leader'?leader.read(o,id):engine.read(o,id);
async function route(method,o,id,revision,...rest){
 const t=await engine.store.get(id,o);
 if(t.revision!==revision)throw new Error('Team changed; refresh before controlling members');
 if(!['stop','pause','reconcile','recoverIntegration'].includes(method)){const current=await projectTeams.current(o,{cwd:t.projectPath});if(current&&current.id!==id)throw new Error('Historical team is read-only; assign work to the project’s current team');}
 if(t.mode!=='host-leader'){if(method==='start')throw new Error('旧隔离团队已停用启动；保留记录和停止/恢复能力。请由当前 Leader 创建原生成员计划。');return engine[method](o,id,revision,...rest);}
 if(method==='reconcile')return leader.receipt(o,id);
 if(['integrate','recoverIntegration'].includes(method))throw new Error('原生成员直接在当前项目工作，无副本写回操作；请完成独立审查与 Leader 最终验收。');
 if(['edit','cancel'].includes(method)){assertPlanMutable(t);await engine[method](o,id,revision,...rest);return leader.receipt(o,id);}
 return leader[method](o,id,revision,...rest);
}
const owner=extra=>runtime.scope(extra?._meta);
// Only field names, never metadata values, credentials, prompts or file content.
function snapshot(extra) {
  const peer = server.server.getClientVersion();
  return {
    kind: 'host-connection-probe', pluginVersion:VERSION, productReady: false,
    observedAt: new Date().toISOString(), bootId, startedAt,
    source: 'live-mcp-connection',
    client: peer ? { name: peer.name, version: peer.version } : null,
    capabilityNames: Object.keys(server.server.getClientCapabilities() ?? {}).sort(),
    metadataNames: Object.keys(extra?._meta ?? {}).sort(),
    projectAuthorization: 'NOT_VERIFIED',
    agentExecution: 'EXPERIMENTAL_FIXTURE_ONLY', agentControl: 'EXPERIMENTAL_UNVERIFIED',
    hostLifecycle: 'NOT_VERIFIED',
    warning: '连接成功不代表能够创建、查询或停止 Agent。'
  };
}
const result = (data) => {
  if(data.kind==='team-detail'&&data.team.mode==='host-leader'&&!data.detailToken){
    const context=responseContext.getStore();
    data=context?.role==='leader'&&context.view!=='summary'?operationResponse(data,context):teamResponse(data,'summary','team-update');
  }
  data={...data,pluginVersion:VERSION};
  const text=responseContext.getStore()?JSON.stringify({kind:data.kind,pluginVersion:VERSION,teamId:data.teamId??data.team?.id,revision:data.revision??data.team?.revision,payload:'structuredContent'}):data.kind==='team-state'||data.displayLimits?.preview?JSON.stringify({kind:data.kind,teamId:data.team.id,revision:data.team.revision,detailToken:data.detailToken,displayLimits:data.displayLimits}):JSON.stringify(data);
  return {content:[{type:'text',text}],structuredContent:data};
};
const readOnly = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const guarded=fn=>async(args,extra)=>requestContext.run(async()=>{try{return result(await fn(args,extra));}catch(error){return {isError:true,content:[{type:'text',text:error.message}]};}});
const teamId={teamId:z.string().uuid()};
const editTeam={...teamId,revision:z.number().int().positive()};
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/);
const routeSchema=z.object({model:z.string().min(1).max(100).optional(),reasoningEffort:z.string().min(1).max(30).optional()});
const policySchema=z.object({tokenLimit:z.number().int().positive().nullable().optional(),contextChars:z.number().int().min(4000).max(100000).optional(),maxAttempts:z.number().int().min(1).max(10).optional(),requireKnownUsage:z.boolean().optional(),autoRepair:z.boolean().optional(),maxReviewRounds:z.number().int().min(1).max(10).optional()});
const memberSchema=z.object({id,role:z.string().min(1).max(100),responsibility:z.string().min(1).max(2000),reason:z.string().min(1).max(1000),writeScopes:z.array(z.string().min(1).max(300)).max(30),route:routeSchema.optional(),fallbackRoute:routeSchema.optional()});
const criteriaSchema=z.array(z.object({id,description:z.string().min(1).max(2000)})).min(1).max(30);
const contractSchema=z.object({stage:z.enum(['requirements','implementation','verification','review','repair','integration']),inScope:z.array(z.string().min(1).max(300)).max(30).default([]),outOfScope:z.array(z.string().min(1).max(300)).max(30).default([]),verify:z.array(z.string().min(1).max(2000)).max(30).default([]),coverageOf:z.array(id).max(30).default([])});
const planSchema=z.object({members:z.array(memberSchema).min(1).max(8),goalCriteria:criteriaSchema.optional(),tasks:z.array(z.object({id,title:z.string().min(1).max(200),goal:z.string().min(1).max(3000),context:z.string().max(12000).optional(),acceptance:z.string().min(1).max(3000),acceptanceCriteria:criteriaSchema.optional(),contract:contractSchema.optional(),memberId:id,priority:z.number().int().min(1).max(5),kind:z.enum(['work','review']).default('work'),validationMode:z.enum(['execute','source-only']).default('execute'),reviewOfTaskId:id.optional(),parentTaskId:id.optional(),resources:z.array(z.string().min(1).max(100)).max(20).default([]),dependencies:z.array(z.object({taskId:id,when:z.enum(['submitted','accepted'])})).max(40)})).min(1).max(40)});
const formationPlanSchema=planSchema.extend({tasks:z.array(planSchema.shape.tasks.element).max(0).default([]).describe('Leave empty: concrete tasks are planned after team confirmation')});
const approvalFields={memberStartup:z.enum(['on-demand','eager']).default('on-demand'),approvalMode:z.enum(['auto','required','immediate']).default('auto'),executionAuthorization:z.string().min(1).max(2000).optional(),brief:z.string().max(3000).optional()};
const legacyConfigurationSchema=z.object({taskPlanning:z.never().optional(),memberStartup:z.enum(['on-demand','eager']).optional(),goal:z.string().min(8).max(2000),plan:planSchema,maxParallel:z.number().int().min(1).max(8),policy:policySchema.optional()});
const configurationSchema=z.union([legacyConfigurationSchema.extend({taskPlanning:z.literal('leader'),plan:formationPlanSchema}),legacyConfigurationSchema]);
const hostContext=new HostContext();
const modelCatalog=new ModelCatalog(hostContext);
const requestContext=new RequestContext(meta=>hostContext.resolve(meta));
const currentProject=extra=>requestContext.project(extra);
async function assertCurrentTeam(extra,teamId){return authorizeTeam({owner:owner(extra),context:await currentProject(extra),store:engine.store,teamId});}
registerAppTool(server,'open_team_workspace',{title:'团队',description:'打开当前 Codex 项目、当前会话关联的团队监管面板。项目来自宿主线程元数据，不要求重新选择项目或填写目标，不启动成员。',inputSchema:{},annotations:readOnly,_meta:{ui:{resourceUri:URI},'openai/ui':{entrypoints:[{type:'thread'}]}}},guarded(async(_,extra)=>{
  const context=await currentProject(extra),current=await projectTeams.current(owner(extra),context),teams=current?[current]:[];
  return{kind:'team-workspace',version:VERSION,context,teams:teams.map(t=>({id:t.id,goal:t.goal,state:t.state,revision:t.revision,updatedAt:t.updatedAt})),observedAt:new Date().toISOString(),productReady:false};
}));
registerAppTool(server,'get_current_project',{title:'读取当前项目上下文',description:'自动读取触发此工具的 Codex 会话项目目录及必要说明。协调者直接沿用当前对话目标；不得要求用户去面板重选项目或重填需求。不会启动模型成员。',inputSchema:{},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(_,extra)=>({context:await currentProject(extra),executionMode:'host-leader',projectScan:false,instructions:'当前主会话就是 Leader。使用当前项目和已有对话上下文；按任务读取必要文件。'})));
registerAppTool(server,'plan_team',{title:'组建当前项目团队',description:'直接用当前对话中用户已给出的目标和当前 Codex 项目组队。先调用 get_current_project 了解项目，只生成成员、职责、写入范围和模型配置；plan.tasks 留空。组建时只确认团队成员和目标，确认后 Leader 用 add_team_tasks 拆分具体任务和独立审查，不逐项要求用户确认。execute=true 表示有执行意图；approvalMode=auto 时新团队先等待成员和目标确认，required 强制先审阅，immediate 仅限用户明确说直接做并记录 executionAuthorization。只要计划时 execute=false。待确认时不得初始化成员；用 read_team_plan 展示团队目标、成员和职责，用户随后在聊天确认可用 approve_team_plan，无需再点面板。',inputSchema:{...approvalFields,goal:z.string().min(8).max(2000),plan:formationPlanSchema,maxParallel:z.number().int().min(1).max(8).default(3),execute:z.boolean().default(false),requestId:z.string().uuid().optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},_meta:{ui:{resourceUri:URI}}},guarded(async(args,extra)=>{
  const o=owner(extra),context=await currentProject(extra);await modelCatalog.freeze(args.plan.members,context);const {team,reused}=await projectTeams.plan(o,context,{...args,taskPlanning:'leader'});
  return {kind:'team-detail',...await leader.receipt(o,team.id),reused,requestedGoal:args.goal,leaderAction:team.planReview?.scope==='initial'&&team.planReview.status==='pending'?'Present read_team_plan and wait for the user to confirm this version. Do not initialize members.':reused?'Reuse this fixed project team. Ordinary in-scope work uses existing authorization; material expansions require a separate plan change.':team.taskPlanning==='leader'&&!team.tasks.length?'Use add_team_tasks to decompose the confirmed goal within the confirmed roster, include independent reviews, then dispatch. Do not request individual task confirmation.':'Claim ready tasks; on-demand members are created with their first task, then reused. Eager mode initializes members first. No model has been launched by plan_team.'};
}));
registerAppTool(server,'archive_team',{description:'Only after explicit user instruction: archive the current completed native team, preserve acceptance and all history, and free the project for a new team. Requires Leader final acceptance, no pending plan changes/reservations, and verified idle native members. Stable UUID safely replays an uncertain save. Never starts/stops members or archives Codex chats.',inputSchema:{...editTeam,requestId:z.string().uuid(),reason:z.string().min(1).max(1000),source:z.enum(['panel-user-action','leader-recorded-user-instruction'])},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(a,e)=>projectTeams.archive(await assertCurrentTeam(e,a.teamId),await currentProject(e),a)));
registerAppTool(server,'rebuild_project_team',{description:'仅在用户明确要求重新组建团队时调用。要求旧成员全部停止并接收终态；归档旧团队并创建替代固定成员团队。普通新任务应 add_team_tasks 复用现有团队。',inputSchema:{...approvalFields,goal:z.string().min(8).max(2000),plan:formationPlanSchema,maxParallel:z.number().int().min(1).max(8).default(3),execute:z.boolean().default(true),requestId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(args,extra)=>{const o=owner(extra),context=await currentProject(extra),{team}=await (async()=>{await modelCatalog.freeze(args.plan.members,context);return projectTeams.rebuild(o,context,{...args,taskPlanning:'leader'});})();return {kind:'team-detail',...await leader.read(o,team.id)};}));
registerAppTool(server,'read_team_plan',{title:'审阅团队计划',description:'按需读取当前确认原文和版本。新团队只包含成员、职责、目标和执行设置；具体任务在确认后由 Leader 拆分。扩展提案和旧版记录保留原内容，不初始化成员。',inputSchema:teamId,annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>leader.readPlan(await assertCurrentTeam(e,a.teamId),a.teamId)));
registerAppTool(server,'revise_team_plan',{title:'调整团队计划',description:'仅修改尚未开工的待确认计划。初始组建只确认成员、职责和目标，taskPlanning=leader 时不得包含具体任务；版本递增，旧确认失效。旧版初始草案可设 taskPlanning=leader 并清空 tasks 转换，历史保留。',inputSchema:{...editTeam,configuration:z.union([configurationSchema,z.object({members:z.array(memberSchema).max(8).default([]),tasks:planSchema.shape.tasks.optional(),policy:policySchema.optional(),maxParallel:z.number().int().min(1).max(8).optional()})]),brief:z.string().max(3000).optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>(async()=>{const o=await assertCurrentTeam(e,a.teamId);await modelCatalog.freeze(a.configuration.plan?.members??a.configuration.members,await currentProject(e));return leader.revisePlan(o,a.teamId,a.revision,a.configuration,a.brief);})()));
for(const [name,action] of [['approve_team_plan','approve'],['cancel_team_plan','cancel']])registerAppTool(server,name,{title:action==='approve'?'确认当前计划':'取消待确认计划',description:'必须来自用户对本版本的明确确认或取消。聊天确认由 Leader 如实记录，不能自行推断或把首次执行意图当作待审计划的批准。绑定 planVersion 和 planHash；重复 UUID 去重。只授权执行，不代表验收，也不直接启动模型。取消扩展仅丢弃提案，保留原团队执行。',inputSchema:{...editTeam,planVersion:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),requestId:z.string().uuid(),note:z.string().min(1).max(2000),source:z.enum(['panel-user-action','leader-recorded-user-confirmation']).default('leader-recorded-user-confirmation')},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await (async()=>{const o=await assertCurrentTeam(e,a.teamId),t=await engine.store.get(a.teamId,o);if(action==='approve'&&t.planReview?.status==='pending')await modelCatalog.validate(t.planReview.scope==='initial'?t.members:t.planReview.pending?.members);const decided=await leader.decidePlan(o,a.teamId,a.revision,a,action);return decided;})()})));
registerAppTool(server,'propose_team_change',{title:'提议团队范围变更',description:'暂存新增岗位、任务、并发或预算变更，确认前不应用、不影响原团队。语义上的目标扩展必须主动使用此工具，不能以普通追加任务绕过确认。',inputSchema:{...editTeam,members:z.array(memberSchema).max(8).default([]),tasks:planSchema.shape.tasks.optional(),policy:policySchema.optional(),maxParallel:z.number().int().min(1).max(8).optional(),brief:z.string().min(1).max(3000)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await leader.proposeChange(await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,{members:a.members,tasks:a.tasks??[],policy:a.policy,maxParallel:a.maxParallel},a.brief)})));
registerAppTool(server,'read_team',{description:'Leader 协调使用 coordination 与上次 cursor：无变化只返回继续等待，变化只含动作、控制和待收件数。仅审查异常或最终结项按任务读取必要证据。summary 返回成员/任务摘要；state/panel 供面板；full 仅显式取证，不用于轮询。panel/full 可用 detailToken。所有读取重新核对当前项目和授权，不启动模型。',inputSchema:{...teamId,view:z.enum(['coordination','summary','state','panel','full']).default('summary'),cursor:z.string().regex(/^[a-f0-9]{64}$/).optional(),detailToken:z.string().regex(/^[a-f0-9]{64}$/).optional()},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(args,extra)=>{
 const o=await assertCurrentTeam(extra,args.teamId);
 if(['full','panel'].includes(args.view)&&args.detailToken){
   const saved=await engine.store.get(args.teamId,o),cached=panelSnapshot.read(o,args.teamId,saved.revision,args.detailToken);
   if(cached)return teamResponse(cached,args.view);
 }
 const data=await readTeam(o,args.teamId);
 if(data.team.mode!=='host-leader'&&!['panel','state'].includes(args.view))return {kind:'team-detail',...data,detailToken:'legacy-full'};
 const projected=teamResponse(data,args.view,'team-summary',{cursor:args.cursor});if(args.view==='state')panelSnapshot.save(o,data,projected.detailToken);return projected;
}));
registerAppTool(server,'request_team_navigation',{title:'定位原生成员会话',description:'校验当前Leader、项目、固定成员和任务轮次；transport=open-link 返回已验证的 codex 会话深链接，由面板直接交给宿主打开，不发消息或启动模型。host-tool 仅兼容旧请求。',inputSchema:{...teamId,memberId:id,taskId:id.optional(),attemptId:z.string().uuid().optional(),destination:z.enum(['member','leader']).default('member'),transport:z.enum(['open-link','host-tool']).default('host-tool'),requestId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>navigation.request(await assertCurrentTeam(e,a.teamId),await currentProject(e),a)));
registerAppTool(server,'read_team_navigation',{description:'核对面板导航请求仍为当前项目、最新有效目标；过期/替换的请求不能执行。只读，不启动模型。',inputSchema:{...teamId,requestId:z.string().uuid()},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>navigation.read(await assertCurrentTeam(e,a.teamId),await currentProject(e),a.teamId,a.requestId)));
registerAppTool(server,'cancel_team_navigation',{description:'用户离开所选任务或成员时取消尚未执行的导航请求；不停止团队或成员。',inputSchema:{...teamId,requestId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>navigation.cancel(await assertCurrentTeam(e,a.teamId),await currentProject(e),a.teamId,a.requestId)));
registerAppTool(server,'record_team_navigation',{description:'记录导航结果。面板 openLink 返回无错误后只能记录 host-accepted，表示宿主接收链接，不证明会话呈现或轮次定位。旧 host-tool 请求由 Leader 按真实工具回执记录 opened/failed。',inputSchema:{...teamId,requestId:z.string().uuid(),status:z.enum(['host-accepted','opened','failed']),note:z.string().min(1).max(2000)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>navigation.record(await assertCurrentTeam(e,a.teamId),await currentProject(e),a)));
for(const [name,method,title] of [['start_team','start','开始执行计划'],['pause_team_dispatch','pause','暂停新任务派发'],['integrate_team','integrate','将全部已验收候选写回项目'],['reconcile_team','reconcile','核对已保存的执行状态，不恢复轮次'],['recover_team_integration','recoverIntegration','回退中断的写回；保留外部新改动，不自动重新写回']])registerAppTool(server,name,{title,description:`${title}。原生团队由当前主会话控制；开始仅允许 Leader 派发，不启动后台调度。仅在用户通过当前对话明确授权后执行；旧版本号请求拒绝，未知状态不自动重试。`,inputSchema:editTeam,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(args,extra)=>({kind:'team-detail',...await route(method,await assertCurrentTeam(extra,args.teamId),args.teamId,args.revision)})));
registerAppTool(server,'read_team_model_catalog',{title:'宿主模型目录',description:'从当前安装的 Codex model/list 读取实际模型与支持的思考档位。短时缓存，不启动模型；不可用时明确报错，不使用编造的模型列表。',inputSchema:{},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(_,e)=>{await currentProject(e);return {kind:'team-model-catalog',...await modelCatalog.read()};}));
registerAppTool(server,'stop_team',{title:'停止团队',description:'暂停派发并记录 stopping，返回全部原生成员（包括初始化轮次）与未知预留。Leader 执行实际中断并 reconcile_team_stop 后才能标记 halted。保存停止请求不等于已停止。',inputSchema:{...editTeam,reason:z.string().min(1).max(2000),requestId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await (async()=>{const o=await assertCurrentTeam(e,a.teamId),t=await engine.store.get(a.teamId,o);return t.mode==='host-leader'?leader.stop(o,a.teamId,a.revision,a):route('stop',o,a.teamId,a.revision,a);})()})));
registerAppTool(server,'reconcile_team_stop',{description:'只核实停止请求，宿主最新轮次未确认结束或预留未知时保持 stopping。unstartedTaskIds 仅限 Leader 已核实尚未送达宿主的绑定预留，必须写实际核对证据；未绑定预留先核实并 release。',inputSchema:{...editTeam,unstartedTaskIds:z.array(id).max(8).default([]),note:z.string().max(2000).default('')},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await leader.reconcileStop(await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a)})));
registerAppTool(server,'resume_team',{title:'恢复团队',description:'仅从已核实 halted 恢复，必须记录原因。只重试 retryTaskIds 中明确选中的停止/失败任务，保留全部历史和预算；不恢复已取消任务，不直接启动模型。',inputSchema:{...editTeam,reason:z.string().min(1).max(2000),requestId:z.string().uuid(),retryTaskIds:z.array(id).max(40).default([])},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{resourceUri:URI,visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await leader.resume(await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a)})));
registerAppTool(server,'amend_team_task_contract',{description:'Leader 修订未通过验收的任务合同，记录原因、旧值、新值和版本，使下游旧证据失效并暂停派发。运行中须先停止并 settle，已提交须先 rework；通过验收的合同冻结。扩大范围另走 propose_team_change，禁止以修订降低或绕过用户验收要求。',inputSchema:{...editTeam,taskId:id,requestId:z.string().uuid(),reason:z.string().min(1).max(3000),patch:z.object({goal:z.string().min(1).max(3000).optional(),acceptance:z.string().min(1).max(3000).optional(),acceptanceCriteria:criteriaSchema.optional(),contract:contractSchema.optional()}).strict()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await leader.amendContract(await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a)})));
registerAppTool(server,'message_team_member',{description:'原生团队持久保存消息并返回 Leader 原生发送提示；requestId 重试去重。保存不是送达，未知结果不自动重发。旧团队沿用其执行端。',inputSchema:{...editTeam,taskId:id,text:z.string().min(1).max(3000),requestId:z.string().uuid().optional()},annotations:{readOnlyHint:false,openWorldHint:true},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await route('message',await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a.taskId,a.text,a.requestId)})));
registerAppTool(server,'edit_team_task',{description:'修改尚未开工任务的分配、优先级或依赖，保留历史并重新校验任务图。',inputSchema:{...editTeam,taskId:id,patch:z.object({memberId:id.optional(),priority:z.number().int().min(1).max(5).optional(),dependencies:z.array(z.object({taskId:id,when:z.enum(['submitted','accepted'])})).optional()})},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await route('edit',await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a.taskId,a.patch)})));
registerAppTool(server,'add_team_tasks',{description:'团队组建确认后，Leader 在已确认目标和职责内拆分或追加具体任务，无需逐项确认；保留历史和独立审查。目标或范围实质扩大必须 scopeChange=true 并写 note，暂存为待确认提案；分配给待批准新岗位的任务也会暂存。语义范围由 Leader 核对，不可自行推定用户已批准扩展。',inputSchema:{...editTeam,tasks:planSchema.shape.tasks,scopeChange:z.boolean().default(false),note:z.string().max(3000).optional()},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await route('addTasks',await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a.tasks,{scopeChange:a.scopeChange,note:a.note})})));
registerAppTool(server,'cancel_team_task',{description:'取消尚未开工的任务及其尚未开工下游，保留历史；已有执行记录时拒绝伪装取消。',inputSchema:{...editTeam,taskId:id,note:z.string().min(1).max(1000)},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await route('cancel',await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a.taskId,a.note)})));
registerAppTool(server,'rework_team_task',{description:'用户明确要求返工时调用；保留所有历史和预算，使下游结论失效。仍运行或未知的相关成员必须先停止并核对。不会自动开工。',inputSchema:{...editTeam,taskId:id,note:z.string().min(1).max(2000)},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>({kind:'team-detail',...await route('rework',await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a.taskId,a.note)})));

const nativeAttempt={...editTeam,taskId:id,attemptId:z.string().uuid()};
const checkpointText=z.string().trim().min(1).max(2000);
registerAppTool(server,'read_team_handoff',{description:'只读当前任务的目标、职责、前置证据和最新检查点，明确历史轮次；不启动或恢复成员。',inputSchema:{...teamId,taskId:id},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const {team,handoff}=await leader.handoff(await assertCurrentTeam(e,a.teamId),a.teamId,a.taskId);return {kind:'team-handoff',team:{id:team.id,revision:team.revision,projectPath:team.projectPath,leaderThreadId:team.leaderThreadId},handoff};}));
const nativeTool=(name,description,inputSchema,fn)=>registerAppTool(server,name,{description,inputSchema,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const o=await assertCurrentTeam(e,a.teamId),t=await engine.store.get(a.teamId,o),current=await projectTeams.current(o,{cwd:t.projectPath});if(current&&current.id!==a.teamId&&!['settle_team_task','release_team_reservation','reconcile_team_message'].includes(name))throw new Error('Historical team is read-only; use the project’s current team');assertPlanExecutable(t);await modelCatalog.freeze(a.members,await currentProject(e));const data=await fn(a,o);return name==='advance_team_workflow'?advancementResponse(data,a.view):{kind:'team-detail',...data};}));
nativeTool('add_team_members','向当前项目的固定团队追加岗位，保留原成员、原生线程、正在执行的任务与历史。传稳定 requestId 重试去重；总人数最多 8。返回新岗位的初始化提示，由 Leader 创建并绑定对应原生 subagent，完成后用 add_team_tasks 分配任务。有计划确认记录的团队先暂存岗位变更，用户确认前不会创建或初始化新岗位；原成员继续工作。',{...editTeam,members:z.array(memberSchema).min(1).max(8),requestId:z.string().uuid()},(a,o)=>leader.addMembers(o,a.teamId,a.revision,a.members,a.requestId,{reviewExpansion:true}));
nativeTool('reassign_team_task','安全改派待执行或阻塞任务，保留每轮执行者、消息、检查点和用量历史。运行中先由 Leader 停止并 settle；已提交或验收任务先显式 rework。目的成员必须保有独立审查和写入范围约束。不会启动、停止模型或重置重试预算。稳定 requestId 去重。',{...editTeam,taskId:id,memberId:id,note:z.string().min(1).max(3000),requestId:z.string().uuid()},(a,o)=>leader.reassign(o,a.teamId,a.revision,a.taskId,a.memberId,a.note,a.requestId));
nativeTool('remove_team_member','移除已确认空闲且没有未完成任务的固定成员；保留其原生线程及全部历史，释放活跃岗位名额。先改派或完成未结束任务，宿主最新轮次未知时拒绝移除。工具不删除或中断原生线程。稳定 requestId 去重；移除后成员 ID 不能重用。',{...editTeam,memberId:id,note:z.string().min(1).max(3000),requestId:z.string().uuid()},(a,o)=>leader.removeMember(o,a.teamId,a.revision,a.memberId,a.note,a.requestId));
registerAppTool(server,'update_team_member_goal',{description:'人工调整已组建团队的角色职责/目标；只影响后续派发，已有任务保留原角色目标快照、任务约定及执行身份。要求当前目标版本和稳定 requestId，保留完整修改历史。直接保存，不发消息、停止成员或启动模型。',inputSchema:{...editTeam,memberId:id,goal:z.string().trim().min(1).max(2000),goalRevision:z.number().int().positive(),requestId:z.string().uuid(),note:z.string().trim().min(1).max(1000),source:z.enum(['panel-user-action','leader-recorded-user-instruction']).default('leader-recorded-user-instruction')},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{
 const o=await assertCurrentTeam(e,a.teamId),t=await leader.native(o,a.teamId),current=await projectTeams.current(o,{cwd:t.projectPath});if(current&&current.id!==t.id)throw new Error('历史团队只读');return leader.updateMemberGoal(o,a.teamId,a.revision,a);
}));
registerAppTool(server,'query_team_tasks',{description:'按任务号、文字、状态或成员分页查询任务摘要与当前轮次；不返回历史提示、交付或日志。按选定任务使用 read_team_context(view=evidence) 读取原始证据，不启动成员。',inputSchema:{...teamId,query:z.string().max(200).default(''),status:z.string().max(30).optional(),memberId:id.optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(200).default(50),cursor:z.string().max(2000).optional()},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const o=await assertCurrentTeam(e,a.teamId),t=await engine.store.get(a.teamId,o);return {kind:'team-query',teamId:t.id,revision:t.revision,...taskQuery(t,a)};}));
registerAppTool(server,'export_team_report',{description:'导出当前项目团队的公开任务、交付和用量报告；无隐藏推理、账号凭据或跨项目记录。',inputSchema:{...teamId,format:z.enum(['markdown','json']).default('markdown')},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const d=await leader.read(await assertCurrentTeam(e,a.teamId),a.teamId);return {kind:'team-export',...exportTeam(d.team,{format:a.format,runs:d.runs,usage:d.usage})};}));
registerAppTool(server,'read_team_recovery',{description:'读取原团队、成员与任务的恢复包，观察真实线程；不恢复模型、不换成员、不把历史线程冒充可控句柄。',inputSchema:teamId,annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const t=await engine.store.get(a.teamId,await assertCurrentTeam(e,a.teamId));return {kind:'team-recovery',...await recoveryPacket(t,leader.observer)};}));
registerAppTool(server,'read_project_team_takeover',{description:'查看当前项目原团队的接续边界及交接；跨 Leader 不伪造宿主接管，不另建团队。',inputSchema:{},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(_,e)=>{const c=await currentProject(e),index=await projectTeams.registry.read(),entry=index.projects[projectTeams.key(c)];if(!entry)return {kind:'team-takeover',status:'no-team'};const t=await engine.store.get(entry.teamId,entry.ownerId);if(t.projectPath!==c.cwd)throw new Error('Project identity mismatch');return {kind:'team-takeover',...takeoverBoundary(t,c.threadId)};}));
nativeTool('record_team_recovery_control','记录 Leader 对原成员实际调用原生工具的结果，失去控制能力时暂停派发，不能用读取成功冒充控制成功。',{...editTeam,memberId:id,threadId:z.string().min(1),status:z.enum(['available','unavailable']),tool:z.string().min(1).max(100),note:z.string().min(1).max(2000)},async(a,o)=>{await engine.store.update(a.teamId,o,a.revision,t=>recordRecoveryControl(t,a));return leader.receipt(o,a.teamId);});
nativeTool('configure_team_policy','调整预算和修复额度。提高预算或自动执行额度时先暂存变更提案，用户确认后才应用；降低额度沿用授权。',{...editTeam,policy:policySchema},(a,o)=>leader.configurePolicy(o,a.teamId,a.revision,a.policy,{reviewExpansion:true}));
nativeTool('advance_team_workflow','一次接收终态，审核通过且插件校验通过后直接登记验收并解锁依赖；Leader 仅处理审查异常与最终结项。默认返回最小处理回执、当前动作和完整派发包，可直接继续或等待，不必再读团队；view=summary 兼容旧摘要。复用有效证据，不重审或重跑相同测试；返回派发包后仍使用原生成员工具，不启动后台协调者。',{...editTeam,view:z.enum(['coordination','summary']).default('coordination'),settleCompleted:z.boolean().default(true),dispatchReady:z.boolean().default(false),decisions:z.array(z.object({taskId:id,attemptId:z.string().uuid(),decision:z.enum(['accept','rework']),note:z.string().min(1).max(2000),nonValidationFailures:z.array(z.object({commandIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).default([]),deferredChecks:z.array(z.object({checkIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).default([])})).max(8).default([])},(a,o)=>leader.advance(o,a.teamId,a.revision,a));
registerAppTool(server,'save_team_profile',{description:'保存可复用的岗位、模型路由与任务模板；不启动成员，不改现有团队身份。',inputSchema:{name:id,taskPlanning:z.enum(['seed','leader']).default('seed'),constraints:z.string().max(6000).default(''),plan:planSchema.extend({tasks:planSchema.shape.tasks.optional()}),policy:policySchema.optional(),note:z.string().max(2000).optional(),expectedUpdatedAt:z.string().optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{await currentProject(e);return {kind:'team-profile',profile:await profiles.save(a.name,a.plan,a.policy,a.note,a)};}));
registerAppTool(server,'read_team_profiles',{description:'读取已保存团队模板，不启动成员。',inputSchema:{name:id.optional()},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{await currentProject(e);return {kind:'team-profiles',profiles:await profiles.read(a.name)};}));
registerAppTool(server,'plan_team_from_profile',{description:'按用户选择的模板组建或复用当前项目固定团队。新团队只确认目标、成员和职责，确认后 Leader 按模板约束拆分具体任务与独立审查；不要求组建时确认任务图。已有团队不替换成员。',inputSchema:{...approvalFields,name:id,maxParallel:z.number().int().min(1).max(8).default(3),goal:z.string().min(8).max(2000),execute:z.boolean().default(false)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await profiles.read(a.name),o=owner(e),c=await currentProject(e),plan={members:structuredClone(p.plan.members),tasks:[]};await modelCatalog.freeze(plan.members,c);const r=await projectTeams.plan(o,c,{...a,plan,policy:p.policy,taskPlanning:'leader'});if(!r.reused)await engine.store.update(r.team.id,o,r.team.revision,t=>{t.profile=a.name;if(p.constraints)t.profileConstraints=p.constraints;});return {kind:'team-detail',...await leader.receipt(o,r.team.id),reused:r.reused,leaderAction:r.team.planReview?.status==='pending'?'Present the team goal and members for confirmation. Do not plan concrete tasks yet.':'Read the selected profile, adapt its constraints and optional seed tasks to the confirmed goal, then add_team_tasks with independent reviews. No individual task confirmation is required.'};}));
nativeTool('prepare_team_worktree','为闲置写入成员准备可选 Git worktree；保留同一原生线程，任务文件操作使用分配目录，无全项目快照。',{...editTeam,memberId:id},async(a,o)=>{await engine.store.update(a.teamId,o,a.revision,async t=>{t.members.find(m=>m.id===a.memberId).workspace=await worktrees.prepare(t,a.memberId);});return leader.receipt(o,a.teamId);});
nativeTool('integrate_team_worktree','已独立验收且所有写入停止后预检并暂存候选合并；不自动提交，冲突预检不修改主项目。',{...editTeam,memberId:id},async(a,o)=>{const saved=await engine.store.update(a.teamId,o,a.revision,async t=>{const integration=await worktrees.integrate(t,a.memberId);t.integrations??=[];if(!t.integrations.some(i=>i.memberId===integration.memberId&&i.candidate===integration.candidate))t.integrations.push(integration);return integration;});return {...await leader.receipt(o,a.teamId),integration:saved.result};});
nativeTool('record_team_peer_delivery','记录 Leader 通过原生工具转交团队成员消息的真实结果；未知送达不能自动重发。',{...editTeam,messageId:z.string().uuid(),status:z.enum(['host-accepted','unknown','failed']),note:z.string().min(1).max(2000)},async(a,o)=>{await engine.store.update(a.teamId,o,a.revision,t=>recordPeerDelivery(t,a));return leader.receipt(o,a.teamId);});
async function participant(extra,tid){const context=await currentProject(extra),saved=await engine.store.document(tid).read();if(!saved.id)throw new Error('Team not found');const t=await engine.store.get(tid,saved.ownerId),member=t.members.find(m=>m.agentThreadId===context.threadId);if(context.cwd!==t.projectPath||!(context.threadId===t.leaderThreadId||(member&&context.parentThreadId===t.leaderThreadId)))throw new Error('Only an authenticated native team participant can access its mailbox');return {team:t,member,context,owner:t.ownerId};}
registerAppTool(server,'read_member_team_work',{description:'当前真实原生成员只读自己被分配的任务、就绪条件和下一步，不领取其他成员工作。',inputSchema:teamId,annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);const work=memberWork(p.team,p.context),task=p.team.tasks.find(t=>t.memberId===p.member?.id&&t.status==='running');return {...work,efficiency:efficiencyAdvice(task?.attempts.at(-1)?.observation)};}));
registerAppTool(server,'read_team_source',{description:'Read a bounded selected project source page. Stable cursor rejects changed content; no binary files or symlink escape. Member can read only current own/dependency task source.',inputSchema:{...teamId,taskId:id,path:z.string().min(1).max(300),startLine:z.number().int().positive().default(1),maxChars:z.number().int().min(256).max(6000).default(4000),cursor:z.string().regex(/^[a-f0-9]{64}$/).optional()},annotations:readOnly},guarded(async(a,e)=>{const p=await participant(e,a.teamId);return readTeamSource(p.team,p.context,a);}));
registerAppTool(server,'prepare_team_command',{description:'Prepare a native command with durable logs, a pre-command input fingerprint and 1200-token output cap. Add verificationInputs for configs/fixtures beyond contract scope. Does not execute, verify or start a model; caller executes exact returned command once in workspace and retains real exit code.',inputSchema:{...teamId,taskId:id,attemptId:z.string().uuid(),requestId:z.string().uuid(),command:z.string().min(1).max(4000),verificationInputs:z.array(z.string().min(1).max(2000)).max(6000).default([])},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);return prepareTeamCommand(leader.root,p.team,p.context,a);}));
registerAppTool(server,'read_team_command_log',{description:'Read at most 6000 characters from one registered command log at a byte offset; preserves full logs on disk. Only original task or authenticated dependency evidence. No synthetic exit codes.',inputSchema:{...teamId,taskId:id,attemptId:z.string().uuid(),requestId:z.string().uuid(),offset:z.number().int().min(0).default(0),maxChars:z.number().int().min(256).max(6000).default(2000)},annotations:readOnly},guarded(async(a,e)=>{const p=await participant(e,a.teamId);return readTeamCommandLog(leader.root,p.team,p.context,a);}));
registerAppTool(server,'read_team_peer_message',{description:'Page one oversized original recipient message without acknowledging a partial read. Read all required pages, then acknowledge its original ID separately. Member identity and exact recipient turn are required.',inputSchema:{...teamId,messageId:z.string().uuid(),attemptId:z.string().uuid().optional(),offset:z.number().int().min(0).default(0),maxChars:z.number().int().min(256).max(2000).default(2000),cursor:z.string().regex(/^[a-f0-9]{64}$/).optional()},annotations:readOnly},guarded(async(a,e)=>{const p=await participant(e,a.teamId),task=p.team.tasks.find(t=>t.memberId===p.member?.id&&t.status==='running'&&t.attempts.at(-1)?.id===a.attemptId),attempt=task?.attempts.at(-1);if(p.member&&!attempt?.turnId)throw new Error('A bound current recipient attempt is required');return {kind:'peer-message-page',...peerMessagePage(p.team,p.context.threadId,{...a,turnId:attempt?.turnId})};}));
registerAppTool(server,'consume_team_inbox',{description:'Read and acknowledge only pending actionable messages for this exact authenticated recipient attempt in one transaction. Bounded page; preserves full history, skips progress and old attempts. Leader may omit attemptId.',inputSchema:{...teamId,attemptId:z.string().uuid().optional(),after:z.number().int().min(0).default(0)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},guarded(async(a,e)=>{
 const p=await participant(e,a.teamId),task=p.team.tasks.find(t=>t.memberId===p.member?.id&&t.status==='running'&&t.attempts.at(-1)?.id===a.attemptId),attempt=task?.attempts.at(-1);
 if(p.member&&!attempt?.turnId)throw new Error('A bound current recipient attempt is required');
 const input={after:a.after,attemptId:a.attemptId,turnId:attempt?.turnId},page=pendingPeerInbox(p.team,p.context.threadId,input);
 if(!page.messages.length)return {kind:'peer-inbox',revision:p.team.revision,...page};
 const r=await engine.store.update(a.teamId,p.owner,p.team.revision,t=>{const selected=pendingPeerInbox(t,p.context.threadId,input);for(const m of selected.messages)acknowledgePeerMessage(t,{messageId:m.id,threadId:p.context.threadId,turnId:attempt?.turnId,attemptId:a.attemptId});return selected;});return {kind:'peer-inbox',revision:r.team.revision,...r.result,acknowledged:true};
}));
registerAppTool(server,'claim_member_team_task',{description:'真实成员在现有原生轮次领取自己就绪的任务。稳定 UUID 去重，检查依赖、预算、并发和独立审查；返回公开回执 marker，继续当前轮次，禁止自行 spawn/followup。',inputSchema:{...editTeam,taskId:id,requestId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);return leader.memberClaim(p.owner,a.teamId,a.revision,p.context,a);}));
registerAppTool(server,'bind_member_team_task',{description:'成员公开发出自己领取任务的 marker 后，绑定当前真实原生线程；只能绑定自己的任务，不允许指定其他线程或替换成员。',inputSchema:{...editTeam,taskId:id,attemptId:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId),r=await leader.memberBind(p.owner,a.teamId,a.revision,p.context,a);return {kind:'member-binding',teamId:a.teamId,revision:r.team.revision,taskId:a.taskId,attemptId:a.attemptId};}));
registerAppTool(server,'report_member_team_task',{description:'成员为自己当前已绑定轮次保存进度、证据和可选交付草稿；明确标记 authenticated-member。提交后仍须输出公开最终交付，只有宿主终态核实后才进入独立审查，不接受成员自验收。',inputSchema:{...editTeam,taskId:id,attemptId:z.string().uuid(),requestId:z.string().uuid(),summary:z.string().trim().min(1).max(3000),decisions:z.array(z.string().min(1).max(2000)).max(30).default([]),remainingWork:z.array(z.string().min(1).max(2000)).max(30).default([]),evidence:z.array(z.string().min(1).max(2000)).max(30).default([]),validation:z.array(z.object({name:z.string().min(1).max(2000),status:z.enum(['PASS','FAIL','BLOCKED','NOT_RUN']),evidence:z.string().min(1).max(2000)})).max(30).default([]),delivery:z.string().min(1).max(24000).optional(),handoff:z.boolean().optional(),verificationInputs:z.array(z.string().min(1).max(300)).max(30).optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);return leader.memberReport(p.owner,a.teamId,a.revision,p.context,a);}));
registerAppTool(server,'send_team_peer_message',{description:'原生成员为当前任务保存给队友或 Leader 的持久消息；Leader 保留实际原生发送控制，保存不等于送达。',inputSchema:{...teamId,attemptId:z.string().uuid(),toMemberId:id,text:z.string().min(1).max(4000),requestId:z.string().uuid(),kind:z.enum(['action','blocker','completion','progress']).default('action')},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);if(!p.member)throw new Error('Use the Leader mailbox tool for Leader messages');const r=await engine.store.update(a.teamId,p.owner,p.team.revision,t=>{const before=t.peerMessages?.length??0,message=queuePeerMessage(t,{...a,senderMemberId:p.member.id,senderThreadId:p.context.threadId});return {message,firstOffer:t.peerMessages.length>before};});const message=r.result.message;return {kind:'peer-message',revision:r.team.revision,message:peerReceipt(message),delivery:'saved-not-sent',nativeAction:r.result.firstOffer&&message.kind!=='progress'?{tool:'send_message',target:message.toMemberId==='leader'?p.member.agentPath?.slice(0,p.member.agentPath.lastIndexOf('/')):r.team.members.find(m=>m.id===message.toMemberId)?.agentPath,threadId:message.recipientThreadId,text:message.marker+'\n'+message.text}:null};}));
registerAppTool(server,'read_team_inbox',{description:'读取当前真实团队参与者的持久收件箱，不能读取其他成员的私有目标收件箱。',inputSchema:{...teamId,after:z.number().int().min(0).default(0)},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);const task=p.team.tasks.find(t=>t.memberId===p.member?.id&&t.status==='running'),attempt=task?.attempts.at(-1);return {kind:'peer-inbox',...(responseContext.getStore()?pendingPeerInbox(p.team,p.context.threadId,{...a,attemptId:attempt?.id,turnId:attempt?.turnId}):peerInbox(p.team,p.context.threadId,a))};}));
registerAppTool(server,'acknowledge_team_peer_message',{description:'原收件成员确认已从收件箱读取指定消息；记录真实原生线程和其当前任务轮次，不代替业务完成。',inputSchema:{...teamId,messageId:z.string().uuid(),attemptId:z.string().uuid().optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId),task=p.team.tasks.find(t=>t.memberId===p.member?.id&&t.status==='running'&&t.attempts.at(-1)?.id===a.attemptId),attempt=task?.attempts.at(-1);if(p.member&&!attempt?.turnId)throw new Error('A bound current recipient attempt is required');const r=await engine.store.update(a.teamId,p.owner,p.team.revision,t=>acknowledgePeerMessage(t,{messageId:a.messageId,threadId:p.context.threadId,turnId:attempt?.turnId,attemptId:a.attemptId}));return {kind:'peer-acknowledgement',message:peerReceipt(r.result),revision:r.team.revision};}));
registerAppTool(server,'read_team_context',{description:'按需读取一个任务。compact 保留完整目标/合同和验收条件；full 返回交接原文。evidence 分页读取指定 attempt 的交付、命令列表、单条命令或输出，默认4000字符，上限8000；hasMore=true 必须继续读所需完整证据后验收。原记录不截断，cursor 防止混用不同结果。',inputSchema:{...teamId,taskId:id,view:z.enum(['compact','full','evidence']).default('compact'),attemptId:z.string().uuid().optional(),section:z.enum(['delivery','commands','command','command-output','checkpoint','verification','review-registration']).default('delivery'),commandIndex:z.number().int().min(0).optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(512).max(8000).default(4000),cursor:z.string().regex(/^[a-f0-9]{64}$/).optional()},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId);if(p.member){const own=p.team.tasks.find(t=>t.memberId===p.member.id&&t.status==='running');const allowed=new Set();function include(id){if(allowed.has(id))return;allowed.add(id);for(const d of p.team.tasks.find(t=>t.id===id)?.dependencies??[])include(d.taskId);}if(own)include(own.id);if(!allowed.has(a.taskId))throw new Error('Only the current task and its dependency contexts may be read');}if(a.view==='evidence')return evidencePage(p.team,a);const {team,handoff}=await leader.handoff(p.owner,a.teamId,a.taskId);return {kind:'team-context',handoff:a.view==='full'?handoff:compactHandoff(handoff,normalizePolicy(team.policy))};}));
registerAppTool(server,'read_team_usage',{description:'读取当前团队时间范围的真实处理量，包含 Leader 和经父级/项目验证的直接原生成员；兜底上下文只记成本，不自动绑定任务。summary 不复制历史任务，full 按需查看分项；未知保留未知，缓存输入不等于账单。派发预算另行强制实时核对。',inputSchema:{...teamId,view:z.enum(['summary','full']).default('summary'),refreshHistorical:z.boolean().default(false)},annotations:readOnly,_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const report=await leader.usage(await assertCurrentTeam(e,a.teamId),a.teamId,a);if(a.view==='summary'){const {tasks,contexts,...usage}=report;return {kind:'team-usage',usage,detailsAccess:{tool:'read_team_usage',view:'full',teamId:a.teamId}};}return {kind:'team-usage',usage:report};}));
registerAppTool(server,'record_team_peer_sender_delivery',{description:'原消息发送成员记录自己调用原生消息工具的实际回执；只限自己当前任务的消息，保存或工具成功不等于成员已读。',inputSchema:{...teamId,messageId:z.string().uuid(),status:z.enum(['host-accepted','unknown','failed']),note:z.string().min(1).max(2000)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{const p=await participant(e,a.teamId),message=p.team.peerMessages?.find(m=>m.id===a.messageId);if(!p.member||message?.senderThreadId!==p.context.threadId)throw new Error('Only the original sender can record its delivery');const task=p.team.tasks.find(t=>t.id===message.taskId);if(task?.attempts.at(-1)?.id!==message.attemptId||task.status!=='running')throw new Error('Original sender attempt is no longer active');const r=await engine.store.update(a.teamId,p.owner,p.team.revision,t=>recordPeerDelivery(t,{...a,source:'authenticated-sender-native-tool'}));return {kind:'peer-delivery',message:peerReceipt(r.result),revision:r.team.revision};}));
nativeTool('bind_team_roster_member','岗位与当前原生执行会话一对一绑定；旧任务会话按代次保留。按 plan 返回的初始化提示创建成员，立即传宿主返回的路径；初始化回执未落盘时保留关联，不能重建。新任务按派发包创建隔离会话；活动或未知轮次不能替换。',{...editTeam,memberId:id,threadId:z.string().min(1).max(200)},(a,o)=>leader.bindRoster(o,a.teamId,a.revision,a.memberId,a.threadId));
nativeTool('bind_team_roster_members','批量绑定 1–8 个固定成员；每个成员独立验证原生身份，全部验证后一次提交。失败无部分绑定；不要重新创建成员。',{...editTeam,assignments:z.array(z.object({memberId:id,threadId:z.string().min(1).max(200)})).min(1).max(8)},(a,o)=>leader.bindRosterMany(o,a.teamId,a.revision,a.assignments));
nativeTool('record_team_checkpoint','Leader 保存当前已绑定轮次的结构化进度；明确标为 Leader 记录，不代替独立验收。同 requestId 重试去重，旧轮次不能冒充当前证据。',{...nativeAttempt,requestId:z.string().uuid(),summary:z.string().trim().min(1).max(3000),decisions:z.array(checkpointText).max(30),remainingWork:z.array(checkpointText).max(30),evidence:z.array(checkpointText).max(30),validation:z.array(z.object({name:checkpointText,status:z.enum(['PASS','FAIL','BLOCKED','NOT_RUN']),evidence:checkpointText})).max(30)},(a,o)=>leader.checkpoint(o,a.teamId,a.revision,a));
nativeTool('record_team_message_delivery','记录 Leader 观察到的宿主发送结果；不是成员已读。保留原始消息与审计。',{...editTeam,messageId:z.string().uuid(),status:z.enum(['host-accepted','unknown','failed']),note:z.string().min(1).max(2000)},(a,o)=>leader.messageDelivery(o,a.teamId,a.revision,a.messageId,a.status,a.note));
nativeTool('reconcile_team_message','核对原始成员轮次的公开消息回执；精确匹配才能记录成员确认，不重发消息。',{...editTeam,messageId:z.string().uuid()},(a,o)=>leader.reconcileMessage(o,a.teamId,a.revision,a.messageId));
nativeTool('claim_team_task','Leader 为就绪任务预留唯一 attempt，返回必要上下文与原生成员派发提示。不启动成员；主会话随后使用宿主 spawn/followup 工具，原样携带 marker。重试同一预留返回同一 attempt。',{...editTeam,taskId:id},(a,o)=>leader.claim(o,a.teamId,a.revision,a.taskId));
nativeTool('claim_team_tasks','一次预留 1–8 个独立就绪任务，返回 dispatches。逐项检查依赖、成员、资源、写范围与并发，全部成功才提交；失败无部分预留。单个任务同样可使用此工具。不启动模型。',{...editTeam,taskIds:z.array(id).min(1).max(8)},(a,o)=>leader.claimMany(o,a.teamId,a.revision,a.taskIds));
nativeTool('bind_team_member','把宿主原生 subagent 绑定到任务。threadId 接受宿主返回的成员路径或线程 ID；验证父会话、项目目录和唯一公开 attempt 回执，拒绝无关聊天和旧轮次。绑定失败应重试读取，不能重新创建成员。',{...nativeAttempt,threadId:z.string().min(1).max(200)},(a,o)=>leader.bind(o,a.teamId,a.revision,a.taskId,a.attemptId,a.threadId));
nativeTool('bind_team_members','批量绑定已派发的当前任务轮次。并行读取每个真实成员，核对 Leader、项目、唯一 marker 后一次提交，失败无部分绑定。返回 titleActions；保留原成员，不重新 spawn。',{...editTeam,assignments:z.array(z.object({taskId:id,attemptId:z.string().uuid(),threadId:z.string().min(1).max(200)})).min(1).max(8)},(a,o)=>leader.bindMany(o,a.teamId,a.revision,a.assignments));
nativeTool('settle_team_task','接收成员终态和交付；审核角色通过且插件当前轮次、合同、证据与质量校验通过后直接登记验收，解锁后续任务。异常保留提交和历史，由 Leader 处理。重复通知返回已有登记，不重审或重跑测试。',nativeAttempt,(a,o)=>leader.settle(o,a.teamId,a.revision,a.taskId,a.attemptId));
nativeTool('reconcile_team_verification','为当前已提交任务补齐真实命令工作目录、终态退出码与历史输入证明。先 dryRun，指定原轮次 commandId；中断历史需原报告文件哈希表/已声明 SHA256 的 manifest，或 prepare_team_command 的预执行指纹。逐项核对候选与完整输入未变后追加审计；保留原报告、旧 null、所有中断与审查记录。不执行命令，不把 BLOCKED 改为 PASS，环境初始化需 commands 中明确 contractCommand 和全部 initializationCommands，完整链须在原报告声明且使用 && 保留失败。manifest 的 roots 选原声明源码/配置根，全部列出文件仍核对。旧准备记录没有预执行指纹时改用原报告 manifest，不能补造历史哈希。不从不透明脚本提取子命令。已有独立 PASS 审查只重试插件门禁，无新审查或测试。查看关联原文用 read_team_context section=verification。',{...nativeAttempt,requestId:z.string().uuid(),note:z.string().min(1).max(3000),dryRun:z.boolean().default(true),commands:z.array(z.object({turnId:z.string().min(1).max(200),commandId:z.string().min(1).max(200),contractCommand:z.string().min(1).max(4000).optional(),initializationCommands:z.array(z.string().min(1).max(4000)).min(1).max(11).optional()})).min(1).max(30),inputProof:z.discriminatedUnion('kind',[z.object({kind:z.literal('submitted-candidate')}),z.object({kind:z.literal('report-file-map'),field:z.string().min(1).max(200),roots:z.array(z.string().min(1).max(2000)).min(1).max(1000),basePath:z.string().min(1).max(2000).default('.')}),z.object({kind:z.literal('report-manifest'),path:z.string().min(1).max(2000),sha256:z.string().regex(/^[a-f0-9]{64}$/),field:z.string().min(1).max(200),roots:z.array(z.string().min(1).max(2000)).min(1).max(1000),basePath:z.string().min(1).max(2000).default('.')}),z.object({kind:z.literal('prepared-command'),requestId:z.string().uuid()})])},(a,o)=>leader.reconcileVerification(o,a.teamId,a.revision,a));
nativeTool('register_team_native_attempts','补登记已获授权、实际存在的原生执行到原任务，不启动模型或重跑。先 dryRun 核对明确的子会话、顺序轮次和逐轮审查目标。中断链必须连续且前序有宿主持久中断证据。完成只登记为提交；恢复历史验收需显式 Leader 决定、原结论证据和全部既有质量门禁。一次提交、revision 防覆盖、requestId 幂等。',{...editTeam,requestId:z.string().uuid(),note:z.string().min(1).max(3000),dryRun:z.boolean().default(true),entries:z.array(z.object({key:id,taskId:id,threadId:z.string().uuid(),agentPath:z.string().min(1).max(200),marker:z.string().min(1).max(200),turnIds:z.array(z.string().uuid()).min(1).max(30),targetKey:id.optional(),targetAttemptId:z.string().uuid().optional(),reviewDecision:z.object({decision:z.enum(['accept','rework']),note:z.string().min(1).max(3000),proofReference:z.string().min(1).max(2000).optional(),nonValidationFailures:z.array(z.object({commandIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).optional(),deferredChecks:z.array(z.object({checkIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).optional()}).optional()})).min(1).max(40)},async(a,o)=>{const result=await leader.registerNative(o,a.teamId,a.revision,a);return a.dryRun?result:{...await leader.receipt(o,a.teamId),registration:result.registration,replayed:result.replayed};});
nativeTool('reconcile_team_review','补登记因插件异常而未验收的原独立 PASS 审查，包括被退回 waiting 的同一完成轮次。默认 dryRun 返回阻塞项和失败命令索引；Leader 根据原证据说明附带失败后一次登记。核对原目标轮次、合同、只读身份、未变候选及所有本轮必验项，自动关联后续合同的 NOT_RUN。保留原报告、中断、失败命令和拒绝历史，不重审、不启动模型或测试。稳定 requestId 幂等。',{...nativeAttempt,requestId:z.string().uuid(),note:z.string().min(1).max(3000),dryRun:z.boolean().default(true),nonValidationFailures:z.array(z.object({commandIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).default([])},(a,o)=>leader.reconcileReview(o,a.teamId,a.revision,a));
nativeTool('accept_team_review','仅处理插件报告的审查异常：Leader 根据不同成员的已提交审查接受或返工。普通 PASS 由 settle/advance 校验登记，无需重复调用。接受仍须有审核 PASS 证据；不能把执行结束当作通过。明确归属于下游合同的额外 NOT_RUN 自动保留并关联后续任务；本轮各验收条件和必验命令仍须 PASS。source-only 旧阶段说明仍支持 deferredChecks。退回 waiting 的已有 PASS 用 reconcile_team_review，不重派。',{...nativeAttempt,decision:z.enum(['accept','rework']),note:z.string().min(1).max(3000),nonValidationFailures:z.array(z.object({commandIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).default([]),deferredChecks:z.array(z.object({checkIndex:z.number().int().min(0),reason:z.string().min(1).max(2000)})).max(30).default([])},(a,o)=>leader.acceptReview(o,a.teamId,a.revision,a.taskId,a.attemptId,a.decision,a.note,a.nonValidationFailures,a.deferredChecks));
nativeTool('finish_team','Leader 最终结项。默认复用已独立验收且输入未变化的 integration 合同证据；可补充已有最终验证 checks。无有效集成证据时不结项；不重复审查或运行测试。',{...editTeam,note:z.string().min(1).max(3000),checks:z.array(z.object({name:z.string().min(1),status:z.enum(['PASS','FAIL','BLOCKED','NOT_RUN']),evidence:z.string().min(1).max(4000)})).max(50).default([]),reuseEvidence:z.boolean().default(true)},(a,o)=>leader.finish(o,a.teamId,a.revision,a.note,a.checks,a.reuseEvidence));
nativeTool('release_team_reservation','仅当 Leader 已确认宿主没有启动该 attempt 时释放未绑定预留。若启动结果不明，保留预留并核对，不得重派。',{...nativeAttempt,note:z.string().min(1).max(2000)},(a,o)=>leader.release(o,a.teamId,a.revision,a.taskId,a.attemptId,a.note));

registerAppTool(server,'wait_team_event',{description:'Wait up to 55 seconds inside the Leader turn for saved controls or a verified native terminal event. Unchanged timeout continues waiting without reading state or inbox. Use this single wait for controls and native terminal events; do not alternate wait_agent plus zero-time probes. Changed/member-terminal includes compact coordination for immediate action without read_team. Reuse returned continuationArgs, including waitCursor, across calls: progress-only saves never wake coordination. Set functions.exec yield_time_ms=60000 to avoid an extra model round before this wait ends. No model, chat injection, automatic dispatch or acceptance.',inputSchema:{...teamId,revision:z.number().int().positive(),waitCursor:z.string().regex(/^[a-f0-9]{64}$/).optional(),timeoutMs:z.number().int().min(0).max(55000).default(55000),observeNative:z.boolean().default(true)},annotations:readOnly,_meta:{ui:{visibility:['model']}}},guarded(async(a,e)=>{
 const o=await assertCurrentTeam(e,a.teamId),team=await leader.native(o,a.teamId);const event=await waitTeamEvent(engine.store,o,a.teamId,{revision:a.revision,waitCursor:a.waitCursor,timeoutMs:a.timeoutMs,signal:e.signal,...(a.observeNative?{observe:()=>leader.terminalSnapshot(o,a.teamId),...(team.tasks.some(t=>t.status==='running'&&t.attempts.at(-1)?.agentThreadId)?{subscribe:notify=>leader.observer.subscribe(team,notify)}:{})}:{})});return ['changed','member-terminal','terminal'].includes(event.status)?{...event,coordination:coordinationResponse(await leader.receipt(o,a.teamId)),readRequired:false,nextTool:event.status==='member-terminal'?'advance_team_workflow':'team_leader'}:event;
}));
registerAppTool(server,'coordinate_team',{description:'Read the native internal coordination contract and legacy notification history. The chat bridge is disabled; reserve never offers a chat message, even for old panel clients. Use native agent messages/completions and wait_team_event for saved panel controls. No model executor or automatic acceptance.',inputSchema:{...teamId,operation:z.enum(['status','enable','reserve','receipt','consume']),enabled:z.boolean().optional(),detailToken:z.string().regex(/^[a-f0-9]{64}$/).optional(),notificationId:z.string().uuid().optional(),retryId:z.string().uuid().optional(),status:z.enum(['host-accepted','failed','unknown']).optional(),note:z.string().max(1000).optional()},annotations:{readOnlyHint:false,openWorldHint:true},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{
 const o=await assertCurrentTeam(e,a.teamId),saved=await leader.native(o,a.teamId);
 const data=['status','enable','receipt'].includes(a.operation)?await leader.receipt(o,a.teamId):panelSnapshot.read(o,a.teamId,saved.revision,a.detailToken)??await leader.read(o,a.teamId);
 if(a.operation==='status')return {kind:'team-coordination',...await coordination.read(o,data)};
 if(a.operation==='enable'){if(typeof a.enabled!=='boolean')throw new Error('Enabled is required');return {kind:'team-coordination',...await coordination.enable(o,data,a.enabled)};}
 if(a.operation==='reserve')return {kind:'team-coordination',...await coordination.reserve(o,data,a)};
 if(a.operation==='receipt')return {kind:'team-coordination',...await coordination.receipt(o,a.teamId,a)};
 if(!a.notificationId)throw new Error('Notification ID is required');
 return {kind:'team-coordination',...await coordination.consume(o,data,a.notificationId)};
}));
registerAppTool(server,'request_team_plan_feedback',{description:'Persist a user request to revise a pending plan. No chat message is sent. Preserve the version-bound draft, stop planning and wait for user feedback. Do not recreate or approve it.',inputSchema:{...editTeam,planVersion:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),requestId:z.string().uuid(),note:z.string().min(1).max(2000)},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>leader.requestPlanFeedback(await assertCurrentTeam(e,a.teamId),a.teamId,a.revision,a)));
registerAppTool(server,'manage_team',{description:'Project-scoped team history, saved profiles, full role goal and its revisions (member-goal), task contract revision history and preapproved model fallback. Archived teams are read-only. Profile deletion requires its observed updatedAt. Fallback never starts a model.',inputSchema:{operation:z.enum(['history','profiles','profile','delete-profile','contracts','member-goal','fallback','capabilities']),teamId:z.string().uuid().optional(),taskId:id.optional(),memberId:id.optional(),name:id.optional(),updatedAt:z.string().optional(),revision:z.number().int().positive().optional(),reason:z.string().min(1).max(2000).optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(50).default(20)},annotations:{readOnlyHint:false,openWorldHint:false},_meta:{ui:{visibility:['app','model']}}},guarded(async(a,e)=>{
 const c=await currentProject(e),o=owner(e);
 if(a.operation==='capabilities')return {kind:'team-capabilities',compactAdvancement:true,selectedEvidenceDefault:true,registrationGapNotice:true,schemaReuse:'explicit-versioned-hash',boundedSourceAndLogPages:true,nativeCommandLogPreparation:true,preCommandInputFingerprint:true,hostWorkingDirectoryVerification:true,historicalVerificationReconciliation:'explicit-native-command-identities-and-unchanged-inputs',commandCapsEnforcement:'helpers-and-dispatch-instructions; direct-native-tools-remain-host-controlled',phaseHandoff:'explicit-completed-checkpoint; max-3; clean-context',phaseVerificationReuse:'successful-host-command-and-unchanged-input-fingerprint',progressWakeCoalescing:true,persistentSemanticWaitCursor:true,declaredInitializationBinding:true,singleWaitWithInlineCoordination:true,combinedInboxAcknowledgement:true,singleCopyRouterPayload:true,singleCopyModelPayloads:true,source:'current-adapter-contract',nativeToolsRequired:true,workflowBridge:'disabled',internalCommunication:'native-agent-messages-and-completions',panelControlWait:'wait_team_event',nativeTerminalEventWait:true,panelWakeWithoutWaiter:false,chatMessages:false,backgroundModelExecutor:false,existingMemberModelChange:false,arbitraryProviderRouting:false,nativeSlashMenuRegistration:false,nativeHeaderSlot:false,nativeTurnAnchor:false,crossLeaderControlTransfer:false,restartControlRestoration:'requires-real-native-tool-receipt',preservesOriginalMemberIdentity:false,preservesLogicalRoleIdentity:true,preservesNativeExecutionHistory:true,taskContextIsolation:true,inPlaceContextReset:false,dispatchContextBudget:'full-prompt-hard-limit',modelCoordinationView:'coordination',unchangedTimeoutRequiresStateRead:false,reviewerAcceptance:'plugin-gated-on-settlement',leaderReviewScope:'exceptions-and-final-closure',finalEvidenceReuse:'accepted-integration-contract-with-unchanged-inputs',evidencePageMaxChars:8000,usageScope:'leader-and-direct-native-children-during-team',usageDisplayCacheMs:10000,budgetVerification:'fresh-before-plugin-dispatch',fallbackContextsExecutionAuthority:false};
 if(a.operation==='history'){const rows=await engine.store.summaries(o,c.cwd),current=await projectTeams.current(o,c);return {kind:'team-history',teams:rows.slice(a.offset,a.offset+a.limit).map(t=>({...t,readOnly:t.id!==current?.id})),total:rows.length,nextOffset:rows.length>a.offset+a.limit?a.offset+a.limit:null,currentTeamId:current?.id};}
 if(a.operation==='profiles')return {kind:'team-profiles',profiles:await profiles.read()};
 if(a.operation==='profile'){if(!a.name)throw new Error('Profile name is required');return {kind:'team-profile',profile:await profiles.read(a.name)};}
 if(a.operation==='delete-profile'){if(!a.name||!a.updatedAt)throw new Error('Read the profile before deleting');return {kind:'team-profile',...await profiles.remove(a.name,a.updatedAt)};}
 if(!a.teamId)throw new Error('Team ID is required');await assertCurrentTeam(e,a.teamId);const team=await leader.native(o,a.teamId);
 if(a.operation==='member-goal'){if(!a.memberId)throw new Error('Member ID is required');return memberGoalDetail(team,a.memberId);}
 if(a.operation==='contracts')return {kind:'team-contracts',teamId:team.id,revision:team.revision,amendments:(team.contractAmendments??[]).filter(r=>!a.taskId||r.taskId===a.taskId).slice(a.offset,a.offset+a.limit),total:(team.contractAmendments??[]).filter(r=>!a.taskId||r.taskId===a.taskId).length};
 if(!a.memberId||!a.reason||!a.revision)throw new Error('Fallback requires member, revision and reason');
 const current=await projectTeams.current(o,c);if(current?.id!==team.id)throw new Error('Historical team is read-only');
 const member=team.members.find(m=>m.id===a.memberId&&!m.removedAt);
 if(!member?.fallbackRoute?.model)throw new Error('This member has no preapproved fallback route');
 if(team.tasks.some(t=>t.memberId===member.id&&['running','submitted'].includes(t.status)))throw new Error('Stop and settle the current attempt before activating fallback');
 await modelCatalog.validate([{route:member.fallbackRoute}]);
 if(member.agentThreadId)throw new Error('This host cannot change the model route of an existing native member. The original thread is preserved; fallback is available only before first spawn.');
 await engine.store.update(team.id,o,a.revision,t=>{assertPlanExecutable(t);if(t.executionControl&&t.executionControl.status!=='active')throw new Error('Explicitly resume the halted team first');const m=t.members.find(m=>m.id===a.memberId);m.activeRoute=structuredClone(m.fallbackRoute);requireTeamVersion(t,'0.14.0');t.events.push({at:new Date().toISOString(),type:'preapproved-fallback-activated',memberId:m.id,reason:a.reason,route:m.activeRoute});});
 return {kind:'team-detail',...await leader.receipt(o,team.id)};
}));
registerAppTool(server,'team_command',{description:'Parse a literal /agent-teams [--profile NAME] GOAL invocation. This is a deterministic plugin protocol entry; it does not register a native host slash-menu item or start members.',inputSchema:{command:z.string().min(1).max(3000)},annotations:readOnly,_meta:{ui:{visibility:['model']}}},guarded(async(a,e)=>{
 const match=/^\/agent-teams(?:\s+--profile\s+([a-zA-Z0-9_-]{1,64}))?(?:\s+([^\r\n]+))?$/.exec(a.command.trim());
 if(!match||match[2]?.startsWith('--'))throw new Error('Use /agent-teams [--profile NAME] GOAL');
 const c=await currentProject(e),current=await projectTeams.current(owner(e),c),profile=match[1]?await profiles.read(match[1]):null;
 return {kind:'team-command',context:c,currentTeamId:current?.id??null,goal:match[2]??current?.goal??null,profile,approval:'required',nativeSlashRegistration:false,instructions:'Reuse the current project team. If no current team exists, design the roster, responsibilities and goal with no concrete tasks, save with approvalMode=required and wait for user approval. Never approve the same planning turn.'};
}));
for(const role of ['leader','member'])registerAppTool(server,'team_'+role,{description:role==='leader'?'Read structuredContent ?? content, forward only that payload. Pass retained schemaHash on schema refresh; matching hash returns unchanged. Leader coordination router. operation is an existing business tool name; arguments are that tool’s input. Read operation=describe with toolName only when its input is unknown; reuse that schema for this pluginVersion, including retries. Do not describe again before each call. operation=directory lists authorized operations. Delegate only through native tools; handle review exceptions and final closure, ordinary PASS is plugin-gated. Mutation replies default to compact receipts; responseView=summary explicitly requests the display preview.':'Read structuredContent ?? content, forward only that payload. Pass retained schemaHash on schema refresh; matching hash returns unchanged. Member router for own assigned work and roster messages only. operation=directory lists the member operations; describe with toolName returns one schema; reuse it for this pluginVersion rather than describing before every call. Never accept work or change team scope.',inputSchema:{operation:z.string().min(1).max(80),toolName:z.string().max(80).optional(),schemaHash:z.string().regex(/^[a-f0-9]{64}$/).optional(),responseView:z.enum(['coordination','summary']).default('coordination'),arguments:z.record(z.string(),z.unknown()).default({})},annotations:{readOnlyHint:false,openWorldHint:true},_meta:{ui:{visibility:['model']}}},async(a,e)=>{
 const allowed=([...operationHandlers.keys()].filter(name=>!compactTools.has(name)&&!debugOperation(name)&&(role==='member'?memberOperations.has(name):!memberOperations.has(name)||sharedOperations.has(name))));
 if(a.operation==='directory')return responseContext.run({role},()=>result({kind:'team-tool-directory',role,operations:allowed,payload:'Use structuredContent ?? content; forward once'}));
 const name=a.operation==='describe'?a.toolName:a.operation;
 if(!allowed.includes(name))return {isError:true,content:[{type:'text',text:'Operation is not available to this role'}]};
 const item=operationHandlers.get(name);
 if(a.operation==='describe')return responseContext.run({role},()=>result(schemaCatalog.describe(name,z.toJSONSchema(z.object(item.options.inputSchema)),item.options.description,a.schemaHash)));
 try{if(role==='leader'&&(await currentProject(e)).parentThreadId)throw new Error('Native members cannot invoke Leader operations');const args=z.object(item.options.inputSchema).parse(a.arguments);return await responseContext.run({role,operation:name,view:a.responseView,taskIds:[args.taskId,...(args.taskIds??[]),...(args.bindings??[]).map(b=>b.taskId)].filter(Boolean)},()=>item.handler(args,e));}catch(error){return {isError:true,content:[{type:'text',text:error.message}]};}
});

registerAppTool(server, 'open_host_probe', {
  title: '宿主连接验证',
  description: '打开 Team Workspace 原型验证面板，读取已有实验状态；打开本身不会启动或恢复 Agent。',
  inputSchema: {}, annotations: readOnly,
  _meta: { ui: { resourceUri: URI }, 'openai/ui': {} }
}, async (_args, extra) => {
  let runs=[];
  if(extra?._meta?.threadId || extra?._meta?.thread_id) runs=await runtime.list(runtime.scope(extra._meta));
  return result({...snapshot(extra),runs});
});

registerAppTool(server, 'read_execution_probe', {
  description:'只读当前宿主会话的原型执行记录，不创建进程或恢复 Agent。',inputSchema:{},annotations:readOnly,
  _meta:{ui:{visibility:['app']}}
},async(_args,extra)=>result({observedAt:new Date().toISOString(),runs:await runtime.list(runtime.scope(extra._meta))}));

const mutations=[
  ['start_execution_probe','启动固定隔离 fixture 的真实 Agent 验证。仅在用户明确授权原型执行和账号用量后调用。','start'],
  ['message_execution_probe','向本会话测试成员发送固定的监督验证消息，正在运行时 steer，空闲时开启新轮次。','message'],
  ['begin_stop_trial','显式启动一个有时间和轮次上限的停止测试，随后应请求停止。','stopTrial'],
  ['stop_execution_probe','请求中断当前测试轮次；只有执行端完成事件才能确认中断。','stop']
];
for(const [name,description,method] of mutations) registerAppTool(server,name,{
  title:description,inputSchema:method==='start'?{}:{runId:z.string().uuid()},description,
  annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:method==='stop',openWorldHint:true},
  _meta:{ui:{resourceUri:URI}}
},async(args,extra)=>{
  try {return result({observedAt:new Date().toISOString(),runs:[await runtime[method](runtime.scope(extra._meta),args.runId)]});}
  catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}
});

registerAppTool(server, 'probe_roundtrip', {
  title: '验证面板工具往返', description: '回传一次性随机标记及 MCP 客户端能力名称；不读写项目，不执行模型。',
  inputSchema: { nonce: z.string().regex(/^[a-f0-9-]{36}$/) }, annotations: readOnly,
  _meta: { ui: { resourceUri: URI, visibility: ['app'] } }
}, async ({ nonce }, extra) => result({ ...snapshot(extra), nonce }));

registerAppResource(server, 'host-probe', URI, {}, async () => ({ contents: [{
  uri: URI, mimeType: RESOURCE_MIME_TYPE,
  text: await readFile(join(__dirname, 'host.html'), 'utf8'),
  _meta: {
    ui: { csp: { connectDomains: [], resourceDomains: [] } },
    'openai/ui': { preferredDisplayMode: 'fullscreen', availableDisplayModes: ['fullscreen'] }
  }
}] }));

server.connect(new StdioServerTransport()).catch((err) => {
  console.error(err.message);
  process.exit(1);
});
// No listeners/autostart. Only explicit start creates the owned app-server child.
// EOF requests interruption and closes that child. Never resume on reload.
let closing=false;
async function shutdown(){if(closing)return;closing=true;try{await hostContext.close();await leader.close();await engine.close();await runtime.close();await server.close();}finally{process.exit(0);}}
process.stdin.once('end',()=>void shutdown());
process.once('SIGTERM',()=>void shutdown());
